import type { Strings } from '../i18n';

/**
 * The English strings. Its own module, loaded on demand (lib/i18n `loadStrings`),
 * so the bundle a visitor downloads carries one language and not both; the
 * other arrives in idle time, in case they switch.
 */
export const en: Strings = {
  appName: 'Thwart',
  tagline: 'Cards, collection, decks and statistics for Marvel Champions',
  seo: {
    homeTitle: 'Thwart — Marvel Champions companion: cards, collection, decks, campaigns',
    homeDescription:
      'A free companion for Marvel Champions: The Card Game. Search every card, track your collection, build decks, draw a game, play the campaigns. Offline, no account.',
    cardTitle: 'Marvel Champions card — Thwart',
    cardTitleNamed: (name) => `${name} — Marvel Champions card — Thwart`,
    cardDescription:
      'Card text, stats, set and pack for Marvel Champions: The Card Game, from MarvelCDB, in English or French.',
    collectionTitle: 'Marvel Champions collection tracker — Thwart',
    collectionDescription:
      'Tick the Marvel Champions packs you own and see which cards, heroes and scenarios you have. Kept on your device, exportable, and synced across devices with an optional account.',
    randomizerTitle: 'Marvel Champions random game generator — Thwart',
    randomizerDescription:
      'Draw a random Marvel Champions game from the packs you own: scenario, modular sets, heroes and aspects, at the difficulty you choose.',
    versusTitle: 'Marvel Champions versus mode — Thwart',
    versusDescription:
      'The two-box versus mode of Marvel Champions, set up from the boxes you own.',
    playTitle: 'Marvel Champions play tracker — Thwart',
    playDescription:
      'Set up a Marvel Champions game, track villain health and main scheme threat, and record the result with your heroes, aspects and modular sets.',
    campaignsTitle: 'Marvel Champions campaign tracker — Thwart',
    campaignsDescription:
      'Play the nine Marvel Champions campaigns — Red Skull, Mad Titan, Galaxy, Mutant Genesis, NeXt Evolution, Age of Apocalypse, Agents of S.H.I.E.L.D., Sinister Motives, Fear No Evil — with every setup step, draw and branch handled for you.',
    rulesTitle: 'Marvel Champions rules reference — Thwart',
    rulesDescription: 'The rules reference for Marvel Champions: The Card Game, searchable.',
    decksTitle: 'Marvel Champions deck builder — Thwart',
    decksDescription:
      'Build and check Marvel Champions decks against the cards you own, import from MarvelCDB, and sort them into folders.',
    draftTitle: 'Marvel Champions draft \u2014 Thwart',
    draftDescription:
      'Draft a Marvel Champions deck from the cards you own: an identity, an aspect, then one card at a time out of a random hand. One to four players on one device.',
    historyTitle: 'Game history — Thwart',
    historyDescription: 'Every Marvel Champions game you recorded, filtered by hero, scenario, result or campaign.',
    statsTitle: 'Statistics — Thwart',
    statsDescription: 'Your Marvel Champions win rates by hero, aspect, scenario, difficulty and table size.',
    accountTitle: 'Account — Thwart',
    accountDescription: 'An optional account to sync Thwart between your devices and the Android app.',
    bggTitle: 'BoardGameGeek — Thwart',
    bggDescription: 'Send your Marvel Champions games to BoardGameGeek from Thwart.',
    notFoundTitle: 'Page not found — Thwart',
    notFoundDescription: 'There is nothing at this address.',
  },
  notFoundTitle: 'There is nothing here',
  notFoundBody: 'That address does not match any page of Thwart. The link may be old, or mistyped.',
  notFoundHome: 'Go to the card search',
  homeIntroTitle: 'Thwart, a Marvel Champions companion',
  homeIntro:
    'Every card of Marvel Champions: The Card Game, in English or French, searchable below. Tick the packs you own, and the site knows which decks you can build, which games you can draw and which campaigns you can play.',
  homeIntroLinks: {
    collection: 'Your collection',
    play: 'Play a game',
    campaigns: 'Campaigns',
    decks: 'Decks',
  },
  homeIntroNote:
    'Free, works offline, nothing to install and no account needed. Also on Android. Unofficial: card data from MarvelCDB; Marvel Champions belongs to Fantasy Flight Games and Marvel.',
  searchPlaceholder: 'Search cards…',
  searchLabel: 'Search cards',
  interfaceLanguage: 'Interface',
  cardLanguage: 'Cards',
  theme: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  trackEncounter: 'Track the villain and the scheme',
  trackEncounterNote:
    'Shows the health and threat trackers while you play. Turn it off if you keep score on the table.',
  playLocation: 'Where you play',
  playLocationNote:
    'Filled in on every game you record. It is remembered from the last one you typed.',
  allTypes: 'All types',
  allFactions: 'All factions',
  allPacks: 'All packs',
  allTraits: 'All traits',
  costFrom: 'Cost from',
  costTo: 'to',
  ownedOnly: 'Only what I own',
  favouritesOnly: 'Only favourites',
  clearFilters: (active) => `Clear ${active} filter${active === 1 ? '' : 's'}`,
  loading: 'Loading the card database…',
  loadError: 'The card database could not be loaded.',
  pageLoadError: 'This page could not be loaded. Reload to get the current version of the site.',
  retry: 'Retry',
  noResults: 'No cards match.',
  noResultsHint: 'Try fewer words, or clear the filters.',
  resultCount: (shown: number, total: number) =>
    shown === total ? `${total} cards` : `${shown} of ${total} cards`,
  showMore: (n) => `Show ${n} more`,
  back: 'Back to search',
  cardNotFound: 'That card is not in the database.',
  traits: 'Traits',
  illustrator: 'Illustrator',
  pack: 'Pack',
  viewOnMarvelCdb: 'View on MarvelCDB',
  resources: 'Resources',
  cost: 'Cost',
  unique: 'Unique',
  dataFrom: 'Card data from',
  dataUpdated: 'Updated',
  legal:
    'Marvel Champions card text and images are the property of Fantasy Flight Games and Marvel. This is an unofficial fan project.',
  footerPatreon: 'Support Thwart on Patreon',
  footerAndroid: 'Thwart for Android',
  footerSource: 'Source on GitHub',
  footerReport: 'Report a bug or write to me',
  statHealth: 'Health',
  statHandSize: 'Hand size',
  statAttack: 'Attack',
  statThwart: 'Thwart',
  statDefense: 'Defence',
  statRecover: 'Recover',
  statScheme: 'Scheme',
  statBoost: 'Boost',
  statThreat: 'Threat',

  navRules: 'Rules',
  rulesTitle: 'Rules Reference',
  rulesSearchHint: 'Search the rules',
  rulesNoResults: 'No rule matches your search.',
  rulesLoadError: 'The rules reference could not be loaded.',
  rulesLoading: 'Loading the rules reference…',
  rulesCount: (shown, total) =>
    shown === total ? `${total} entries` : `${shown} of ${total} entries`,
  rulesCreditBefore: 'Compiled by',
  rulesCreditAfter: (licence) =>
    `and released under ${licence}, which is the only reason it can be included here. Unofficial, and not endorsed by Fantasy Flight Games.`,
  navCampaigns: 'Campaigns',
  campaignsTitle: 'Campaigns',
  campaignsEmpty: 'No campaigns here.',
  campaignsEmptyHint:
    'Import a backup from the Android app on the Collection page and your campaigns will show up.',
  campaignProgress: (done, total) => `${done} of ${total} scenarios beaten`,
  campaignConceded: 'conceded',
  campaignFinished: 'finished',
  campaignPlays: (n) =>
    n === 1
      ? '1 recorded play belongs to this campaign.'
      : `${n} recorded plays belong to this campaign.`,
  campaignUnread: (n) =>
    n === 1
      ? "1 event in this campaign's log is not read by this page."
      : `${n} events in this campaign's log are not read by this page.`,
  attempts: (n) => `${n} attempts`,
  navPlay: 'My own setup',
  navHistory: 'History',
  statsRecord: 'Record',
  statsSeeHistory: (games) => `See all ${games} games in the history`,
  loadingGames: 'Reading your games…',
  historyTitle: 'History',
  historyFilters: 'Narrow the history',
  historyFrom: 'From',
  historyTo: 'To',
  historyAny: 'Any',
  historyResult: 'Result',
  historyInACampaign: 'In a campaign',
  historyOutsideACampaign: 'Outside a campaign',
  historyClear: 'Clear the filters',
  historyCount: (shown, total) =>
    shown === total ? `${total} games` : `${shown} of ${total} games`,
  historyEmpty: 'No games recorded yet.',
  historyEmptyHint:
    'Record one from Your own game, or import a backup from the Android app on the Collection page. Everything you play shows up here.',
  historyNoMatches: 'No game matches these filters.',
  historyNoMatchesHint: 'Widen the range, or clear them and start again.',
  historyRunEmpty: 'No scenario recorded against this campaign yet.',
  historyDeleteConfirm:
    'This removes the game from every device and from your statistics. It is kept as a deleted row so the removal can travel, and so it can be undone.',
  navStats: 'Stats',
  playTitle: 'My own setup',
  playSetupNote: 'Choose everything yourself. The clock runs while you play.',
  choose: 'Choose…',
  standardSetWith: 'Standard set played with it',
  seats: 'Decks & players',
  addDeck: 'Add a deck',
  noSeatsYet: 'Add at least one deck.',
  noDecksForPlay:
    'A player is a deck, so there is nothing to add yet. Import one on the Decks page and it will appear here.',
  modularChooseNote:
    'Whatever you actually shuffled in. Only sets from packs you own are listed.',
  startGame: 'Start the game',
  pauseClock: 'Pause the clock',
  resumeClock: 'Resume the clock',
  recordResult: 'Record the result',
  location: 'Where you played',
  victoryPoints: 'Victory points',
  notes: 'Notes',
  won: 'Won',
  lost: 'Lost',
  discardGame: 'Forget this game',
  discardNote:
    'Discarding records nothing: no play in your history and nothing in your statistics.',
  playRecorded: 'Recorded.',
  playAnother: 'Play another',
  statsTitle: 'Statistics',
  statsEmpty: 'No games recorded yet.',
  statsEmptyHint:
    'Record one from My own setup, or import a backup from the Android app on the Collection page.',
  statsNote:
    'Counted per seat, so a four-player game credits all four heroes rather than only the first.',
  winRateOf: (won, total) => `${won} won of ${total} ${total === 1 ? 'game' : 'games'}`,
  timePlayed: (formatted) => `${formatted} at the table`,
  wonOf: (won, played) => `${won}/${played}`,
  byHero: 'By hero',
  byAspect: 'By aspect',
  byHeroAspect: 'By hero and aspect',
  byScenario: 'By scenario',
  byDifficulty: 'By difficulty',
  byPlayerCount: 'By number of players',
  playerBucket: (bucket) =>
    ({
      players_1: 'Solo',
      players_2: 'Two players or two hands',
      players_3: 'Three players',
      players_4: 'Four players',
      // Should never appear: this is a one to four player game, so a row
      // here is a game recorded wrongly and saying so is more use than
      // folding it into the fours.
      players_5plus: 'More than four',
    })[bucket] ?? bucket,
  navDecks: 'Decks',
  deckName: 'Deck name',
  deckSave: 'Save',
  deckContents: 'In the deck',
  deckAddCards: 'Add cards',
  deckEmpty: 'Nothing in it yet. Search on the right and press the plus.',
  deckHeroCards: 'Hero cards',
  deckTabDeck: 'Deck',
  deckTabPool: 'Cards',
  deckProblems: (n) => (n === 1 ? '1 problem' : `${n} problems`),
  factionLabel: 'Aspect',
  typeLabel: 'Type',
  sortLabel: 'Sort',
  sortByName: 'by name',
  sortByCost: 'by cost',
  deckHeroCardsFixed: 'In every deck this hero builds, at the printed count.',
  deckAddHeroCards: 'Add the hero\u2019s cards',
  deckOwnedOnlyEmpty: 'Your collection is empty, so nothing can match. Tick your packs on the Collection page, or untick this to see every card.',
  deckStats: 'What it is made of',
  deckCopy: 'Copy as text',
  deckCopied: 'Copied',
  deckEdit: 'Edit',
  deckNew: 'Build a deck',
  deckPickHero: 'Hero',
  deckPickAspect: 'Aspect',
  deckCreate: 'Start building',
  deckCardCount: (total, min, max) => `${total} cards (${min}\u2013${max})`,
  deckAverageCost: (average) => `Average cost ${average}`,
  deckResources: (physical, mental, energy, wild) =>
    `Resources: ${physical} physical, ${mental} mental, ${energy} energy, ${wild} wild`,
  deckTooFew: (actual, required) => `Only ${actual} cards. A deck needs ${required}.`,
  deckTooMany: (actual, allowed) => `${actual} cards. A deck takes at most ${allowed}.`,
  deckWrongAspects: (actual, required) =>
    `${actual} aspect${actual === 1 ? '' : 's'} chosen; this hero takes ${required}.`,
  deckOffAspect: (card) => `${card} is not in an aspect this deck can take.`,
  deckOverLimit: (card, quantity, limit) =>
    `${quantity} copies of ${card}, and ${limit} ${limit === 1 ? 'is' : 'are'} the limit.`,
  deckDuplicateUnique: (card) => `${card} is unique: only one copy, counting the hero.`,
  deckMissingRequired: (card, required, actual) =>
    `${card} is one of the hero's own cards: ${required} needed, ${actual} in the deck.`,
  deckUnbalanced: (counts) => `The chosen aspects must contribute equally (${counts}).`,
  decksTitle: 'Decks',
  decksOf: (handle) => `${handle}’s decks`,
  decksOfThisBrowser: 'Decks on this browser',
  decksCount: (n) => (n === 1 ? '1 deck' : `${n} decks`),
  foldersCount: (n) => (n === 1 ? '1 folder' : `${n} folders`),
  cardsInDecks: (n) => (n === 1 ? '1 card in decks' : `${n} cards in decks`),
  folderLabel: 'Folder',
  folderNone: 'No folder',
  folderNew: 'New folder',
  folderNamePlaceholder: 'Folder name',
  folderCreate: 'Create',
  folderRename: 'Rename',
  folderDelete: 'Delete folder',
  folderDeleteConfirm: (name) => `Delete the folder \u201c${name}\u201d? Its decks stay.`,
  deckLegal: 'This deck is legal.',
  deckLegalShort: 'legal',
  deckIllegalShort: 'not legal',
  draft: {
    title: 'Draft',
    intro:
      'A deck built one pick at a time, as in a Magic draft: an identity, an aspect, then a hand of random cards from your collection, keep one, again. One to four players on this device, taking turns; every deck ends legal and lands on the shelf.',
    noHeroes: 'No identity in your collection. Tick the packs you own on the Collection page first.',
    resume: 'A draft is in progress.',
    players: 'Players',
    synergy: 'Leave out cards without synergy with the identity',
    synergyDetail: 'Cards that call for a trait the identity lacks are not offered. Cards without a condition always are.',
    identityMode: 'Identities',
    modeRandom: 'Random',
    modeRandomOfFive: 'Random among five',
    modeChoice: 'Chosen',
    offerSize: 'Cards offered at each pick',
    offerSizeDetail: 'More choice makes a smoother deck; fewer, a wilder ride.',
    begin: 'Choose identities',
    playerN: (n) => `Player ${n}`,
    identityTitle: (n) => `Player ${n}: identity`,
    identityDrawn: 'Drawn for you',
    drawAgain: 'Draw again',
    chooseIdentity: 'Choose an identity',
    chooseOfFive: 'Choose one of the five',
    searchHeroes: 'Search identities\u2026',
    takenBy: (n) => `Taken by player ${n}`,
    aspectsTitle: 'Aspect',
    aspectsImposed: 'This identity plays all four aspects; its rule decides.',
    aspectsPickN: (n) => `Choose ${n}`,
    aspectsDraw: 'Draw at random',
    deckSize: 'Deck size',
    deckSizeDetail: (cards, signature, picks) => `Cards: ${cards}. From the identity: ${signature}. Picks: ${picks}.`,
    next: 'Next',
    startDraft: 'Start the draft',
    shortfallTitle: 'Not enough cards on the shelf',
    shortfallLine: (player, needed, available) => `Player ${player}: cards needed, ${needed}; on the shelf with these aspects, ${available}.`,
    shortfallHint: 'Lower a deck size, choose other aspects, or turn the synergy option off.',
    picksMade: (made, total) => `${made} / ${total} picks made`,
    round: (n) => `Round ${n} \u00b7 pick one card`,
    yourDeck: 'Your deck',
    identity: 'Identity',
    handOver: (n) => `Player ${n}\u2019s turn`,
    handOverDetail: 'Pass the device. The previous pick is out of sight.',
    reveal: 'Show my hand',
    nothingLeft: 'Nothing legal is left on the shelf for this deck. It stops here, short of its size.',
    stopHere: 'Stop here',
    abandon: 'Abandon the draft',
    abandonConfirm: 'Abandon this draft? The picks made so far are lost.',
    finishTitle: 'Name the decks',
    finishDetail: 'Each deck goes through the usual check, then all of them are saved at once.',
    deckName: 'Deck name',
    finish: 'Finish the draft',
    saved: (n) => (n === 1 ? 'The deck is on the shelf.' : `${n} decks are on the shelf.`),
    illegal: (name, problems) => `${name} is not legal (${problems} problem${problems === 1 ? '' : 's'}) \u2014 this is a bug, and nothing was saved. The details are in the browser console.`,
    short: (name, cards, size) => `${name} stopped at ${cards} of ${size} cards and cannot be saved. The others can.`,
  },
  synergyIssue: (names) =>
    names.length === 1
      ? `Synergy issue: ${names[0]} has no synergy with this identity`
      : `Synergy issue: ${names[0]} (and ${names.slice(1).join(', ')}) has no synergy with this identity`,
  synergyHideIncompatible: 'Hide cards without synergy with this identity',
  deckIllegal: (n) =>
    n === 1 ? '1 problem with this deck:' : `${n} problems with this deck:`,
  deckLegalityUnknown:
    'The hero card is not in the database, so this deck cannot be checked against the rules.',
  deckComposition: 'Composition',
  deckByType: 'By type',
  deckByAspect: 'By aspect',
  averageCost: (avg) => `Average cost ${avg}`,
  resourceName: (key) =>
    ({ physical: 'physical', mental: 'mental', energy: 'energy', wild: 'wild' })[key] ?? key,
  problemAspectCount: (chosen, expected) =>
    `This hero takes ${expected} ${expected === 1 ? 'aspect' : 'aspects'}; the deck names ${chosen}.`,
  problemTooFew: (actual, minimum) => `${actual} cards, fewer than the ${minimum} minimum.`,
  problemTooMany: (actual, maximum) => `${actual} cards, more than the ${maximum} maximum.`,
  problemRequired: (card, required, actual) =>
    `${card}: the hero's own cards are not optional (${required} required, ${actual} present).`,
  problemOffAspect: (card, faction) =>
    `${card} is ${faction}, which this deck has not taken.`,
  problemCopyLimit: (title, total, limit) =>
    `${total} copies of ${title}; the limit is ${limit}.`,
  problemDuplicateUnique: (title, total) => `${total} copies of ${title}, which is unique.`,
  problemUnbalanced: (counts) => `This hero's aspects must contribute equally: ${counts}.`,
  importDeck: 'Import from MarvelCDB',
  importDeckNote:
    'Paste a decklist link, or just its number. The deck is stored in this browser, keyed the same way the Android app keys it, so importing it in both places gives you one deck rather than two.',
  importAction: 'Import',
  importing: 'Importing…',
  deckImportNotFound:
    'No deck there. Published decklists always work; a personal deck only works if its owner has shared it.',
  deckImportNetwork: 'Could not reach MarvelCDB.',
  noDecks: 'No decks yet.',
  removeDeck: 'Remove',
  cardCount: (n) => `${n} cards`,
  deckMissing: (cards, packs) =>
    `${cards} cards in this deck are not in your collection, from ${packs} packs you do not own.`,
  deckBuildable: 'You own everything in this deck.',
  deckUnknownCards: (n) =>
    `${n} cards in this deck are not in the card database yet. MarvelCDB enters new cards as volunteers get to them.`,
  notOwned: 'not owned',
  deckLocaleNote: (locale) =>
    `Card names are shown in ${locale === 'fr' ? 'French' : 'English'}, following the card language above.`,
  navRandomizer: 'Random game',
  navDraft: 'Draft',
  navVersus: 'Versus',
  versusTitle: 'Versus game',
  versusIntro:
    'Each team builds a scenario and hands it to the other, so what a team faces here is the enemy leader and the enemy schemes.',
  versusNeedsBox:
    'Versus needs a box that has the mode. Record one in your collection and this comes back.',
  versusBox: 'Box',
  versusFaces: 'This team faces:',
  versusLeader: 'Leader',
  versusStageOne: 'Main scheme, stage 1',
  versusStageTwo: 'Main scheme, stage 2',
  versusPlayers: 'Players on this team',
  versusStart: 'Start the game',
  versusEndRound: 'End the round on both boards',
  versusRound: (round) => `Round ${round}`,
  versusWhoWon: 'Who won?',
  versusTie: 'A tie',
  versusAgain: 'Another game',
  versusTiebreakTitle: 'Tie-breaks, in order',
  versusTiebreaks: [
    'The team whose enemy main scheme deck did not advance past stage 1B.',
    'The team with the fewest minions and side schemes in their area.',
    'The team with the least threat on the main scheme in their area.',
    'The team whose identities have the most hit points left.',
    'The team with the fewest attachments on their leader.',
  ],
  filters: 'Filters',
  filtersNote:
    'These apply to this session only and are not saved. What you own lives on the Collection page; this is what you fancy tonight.',
  aspects: 'Aspects',
  excludeBeaten: (n) =>
    n === 0 ? 'Skip scenarios I have beaten' : `Skip scenarios I have beaten (${n})`,
  resetFilters: 'Allow everything again',
  savedDraws: 'Saved draws',
  beatenNote: 'Tick a scenario once you have beaten it, and the filter above can skip it.',
  randomizerTitle: 'Random game',
  randomizerNoCollection:
    'Tick the packs you own on the Collection page first. The draw only offers what you can actually put on the table.',
  randomizerNotEnough: (players) =>
    `Not enough in your collection for ${players} players. Add packs, or play with fewer.`,
  poolNote: (scenarios, heroes, modulars) =>
    `Drawing from ${scenarios} scenarios, ${heroes} heroes and ${modulars} modular sets.`,
  players: 'Players',
  roll: 'Roll',
  reroll: 'Roll again',
  lockField: 'Keep this when rolling again',
  scenario: 'Scenario',
  difficultyLabel: 'Difficulty',
  difficulty: (id) =>
    ({
      STANDARD_I: 'Standard I',
      STANDARD_II: 'Standard II',
      STANDARD_III: 'Standard III',
      EXPERT_I: 'Expert I',
      EXPERT_II: 'Expert II',
    })[id] ?? id,
  heroes: 'Heroes',
  aspect: (id) =>
    ({
      aggression: 'Aggression',
      justice: 'Justice',
      leadership: 'Leadership',
      protection: 'Protection',
      pool: 'Pool',
    })[id] ?? id,
  required: 'required',
  noModularSets: 'This scenario takes no modular sets.',
  saveToHistory: 'Save this draw',
  savedToHistory: 'Saved',
  wave: (n) => `Wave ${n}`,
  waveUnknown: 'Not yet classified',
  navCards: 'Cards',
  navCollection: 'My collection',
  navPlayShort: 'Play',
  navMore: 'More',
  hubStart: 'Start a game',
  hubRandomDetail: 'Let the app pick a scenario, heroes and aspects from what you own.',
  hubOwnDetail: 'Choose everything yourself. The app times the game.',
  hubCampaignDetail: 'Start a campaign, or open one you have finished.',
  hubPaused: 'A game is waiting',
  settingsGroupedPlay: 'One Play tab',
  settingsGroupedPlayHint:
    'Puts the random game, your own setup, the campaigns and versus behind a single Play tab, the way the Android app does.',
  navMoreTitle: 'Everything else',
  settingsTitle: 'Settings',
  close: 'Close',

  accountTitle: 'Account',
  accountSignIn: 'Sign in',
  accountCreate: 'Create an account',
  accountForgot: 'Lost your password',
  accountRecoverAction: 'Reset the password',
  accountHandle: 'Pseudonym',
  accountPassword: 'Password',
  savedOnServer: 'On the server',
  savedLocalOnly: 'On this device only',
  registeredCheckMail: (address) =>
    `The account exists, and it is disabled until you open the link sent to ${address}. Check the spam folder if it is not there.`,
  registeredThenSignIn:
    'Registering does not sign you in. Open the link, then sign in here — on this device and on any other you want kept in step.',
  accountYourData: 'Your data',
  accountExport: 'Download my data',
  accountExporting: 'Preparing…',
  accountExportNote:
    'Everything this account holds on the server, as the same file the app reads and writes. Yours to keep, to move elsewhere, or to check.',
  accountDeleteTitle: 'Delete this account',
  accountDelete: 'Delete my account',
  accountDeleteNote:
    'Removes the account and everything synced to it: your address, your decks, your games, your campaigns and your collection. It does not come back, and it is not the same as signing out. What is on this device stays on this device.',
  accountDeleteConfirm:
    'This deletes the account and everything on the server. There is no undo. Type your password to confirm.',
  accountDeleteYes: 'Delete it permanently',
  verifyTitle: 'Confirming your address',
  verifyWorking: 'One moment.',
  verifyDone: (handle) => `Confirmed. The account ${handle} is now working.`,
  verifyDoneHint:
    'Sign in on whichever devices you want to keep in step. This browser is not signed in by opening a link.',
  verifyFailedHint:
    'A link works once and expires after a week. Ask for a new one from the account screen.',
  verifyGoToAccount: 'Go to the account',
  verifyPendingTitle: 'Confirm your address',
  verifyPendingBody: (address) =>
    `The account is disabled until you open the link sent to ${address}. Nothing syncs until then. If it never arrived, check the spam folder and then ask for another.`,
  verifyResend: 'Send the link again',
  verifyResent: 'On its way. It can take a minute.',
  verifyAlready: 'That address is already confirmed.',
  accountNewPassword: 'New password',
  accountRecoveryCode: 'Recovery code',
  accountDeviceName: 'Name for this browser',
  accountDeviceNameNote:
    'Shown in your list of devices, so you can tell them apart and sign one out.',
  accountManage: 'Manage the account',
  accountClosed:
    'This server is not taking new accounts at the moment. If you have one already, sign in — and if you have lost the password, the recovery code still works.',
  navSignIn: 'Login',
  accountEmail: 'Email address',
  accountEmailNote:
    'This is what you sign in with. It is used for nothing else \u2014 no newsletter, no analytics, and it is never passed to anybody.',
  accountHandleNote: 'The name on your account. You sign in with your address, not with this.',
  accountPasswordRule:
    'At least 12 characters. A phrase you will actually remember beats a short password with symbols in it. It cannot contain your pseudonym or your address.',
  accountRecoveryNote:
    'You also get a recovery code, once. Until this server can send email, that code is the only way back in if you forget your password \u2014 so keep it.',
  accountSignedInAs: 'Signed in as',
  accountDeviceIs: (name) => `This browser is registered as \u201c${name}\u201d.`,
  accountDevices: 'Devices',
  accountThisDevice: 'this one',
  accountLeaving: 'Signing out',
  accountSignOut: 'Sign out',
  accountSignOutKeeps:
    'Everything on this browser stays exactly where it is. Signing out forgets the account, not your collection, decks, plays or campaigns.',
  accountWhy: 'What an account is for',
  accountWhyBody:
    'One place your collection, decks, plays and campaigns live, so the same data is on your phone and in this browser. Until then, the backup file on the Collection page is how it travels.',
  accountPrivacy:
    'The server stores your records without reading them: it does not know what a card is. Your address is kept to sign you in and for nothing else. You can export everything or delete the account outright, and neither needs anybody\u2019s permission.',
  accountError: (code) =>
    ({
      invalid_credentials: 'That address and password do not match an account.',
      email_taken: 'There is already an account on this server with that address.',
      handle_taken: 'That pseudonym is taken on this server. Try another.',
      invalid_email: 'That does not look like an email address.',
      invalid_handle:
        'A pseudonym is 3 to 32 characters: letters, digits, dot, dash or underscore.',
      weak_password:
        'That password is too easy. Use at least 12 characters, and nothing containing your pseudonym or your address.',
      registration_closed: 'This server is not taking new accounts.',
      invalid_recovery_code: 'That recovery code is not right for this account.',
      rate_limited: 'Too many attempts. Wait a little and try again.',
      server_busy: 'The server is busy. Try again in a moment.',
      unauthorized: 'You have been signed out. Sign in again.',
      offline: 'The server could not be reached. Check your connection.',
    })[code] ?? 'Something went wrong on the server. Try again.',
  recoveryTitle: 'Keep this code',
  recoveryIntro:
    'This is shown once and never again. This server cannot send email yet, so until it can, this code is the only way back in if you forget your password. Save it somewhere you will still have it in a year.',
  recoveryDownload: 'Save as a file',
  recoveryCopy: 'Copy',
  recoverySaved: 'I have saved it somewhere safe',
  recoveryDone: 'Done',
  recoveryFileBody: (handle, code) =>
    [
      'Thwart \u2014 account recovery code',
      '',
      `Account: ${handle}`,
      `Code:    ${code}`,
      '',
      'This code resets the password on this account. It is shown once and',
      'the server keeps only a hash of it, so this file is the only copy.',
      'Anyone holding it can take the account: keep it as you would a key.',
    ].join('\n'),
  collectionTitle: 'Collection',
  bulkLabel: 'Add at once:',
  bulkAll: 'Everything',
  bulkCore: 'Core sets',
  bulkHeroes: 'Hero packs',
  bulkScenarios: 'Scenario packs',
  bulkCampaigns: 'Campaign boxes',
  bulkClear: 'Clear the collection',
  bulkClearConfirm: (owned) =>
    `This forgets all ${owned} packs, quantities included. It does not come back.`,
  bulkClearYes: 'Clear it',
  collectionIntro:
    'Tick the packs you own. This is stored in this browser only; nothing is sent anywhere, and there is no account. Use the export below to carry it to another device.',
  collectionOwned: (owned, total) => `${owned} of ${total} packs owned`,
  storageUnavailable:
    'This browser will not let the site store data, so the collection cannot be saved. A private window or blocked site data is the usual cause.',
  copiesOwned: 'Copies owned',
  showContents: 'Contents',
  hideContents: 'Hide',
  contentsHint:
    'Owning a pack is not the same as owning everything in it. Untick anything missing from your copy and the randomiser will not offer it.',
  scenarios: 'Scenarios',
  modularSets: 'Modular sets',

  tracker: 'Villain and scheme',
  trackerLoading: 'Reading the scenario…',
  trackerUnavailable: 'This scenario has no numbers to count.',
  trackerStarred: 'The card prints a star, so type the number',
  trackerStarredAcceleration:
    'This scheme accelerates by a starred amount that depends on the board, so nothing is added for it here — move the threat yourself at the end of the round.',
  trackerNote:
    "Counters only. It does not know that drones enter play or that a Crisis icon stops thwarting, because a tracker that half-adjudicates rules is wrong at somebody's table, and then the numbers it is keeping stop being trusted either.",
  round: (n) => `Round ${n}`,
  endRound: 'End the round',
  advanceVillain: 'Flip the villain',
  advanceScheme: 'Advance the scheme',
  whichScheme: 'Which one is on the table',

  longBreak: 'Take a long break?',
  longBreakIntro:
    'For a table that has to be cleared, or left for a week. The clock stops and where everything stood is written down. One game at a time: saving replaces whatever was already put away.',
  longBreakPhase: 'It stopped in',
  phasePlayer: 'The player phase',
  phaseVillain: 'The villain phase',
  villainStep: (step) =>
    ({
      PLACE_THREAT: 'Placing threat on the main scheme',
      ACTIVATE_MINIONS: 'Activating minions',
      DEAL_ENCOUNTERS: 'Dealing encounter cards',
      REVEAL_ENCOUNTERS: 'Revealing encounter cards',
      PASS_FIRST_PLAYER: 'Passing the first player token',
    })[step] ?? step,
  heroLives: 'Hit points left',
  villainLifeLeft: 'Hit points left on the villain',
  villainStageLabel: 'Which villain card is face up',
  putAway: 'Take the break',
  savePutAway: 'Save and leave the table',
  resumeSaved: 'Pick it up again',
  discardSaved: 'Throw it away',
  savedGame: (scenario, when) => `${scenario}, put away ${when}`,
  savedGameNote:
    'Picking it up puts the cards and the clock back where they were. The clock comes back stopped, because getting the cards out again is not play time.',

  goToSetup: 'Go to setup',
  play: 'Play',
  backToSetup: 'Change the setup',
  clockStartsNote: 'The clock starts when you press Play, not before. Laying a game out takes several minutes and counting them made every game look longer than it was.',
  briefingTitle: 'Preparation',
  briefingIntro: 'What to fetch, and what the scenario says to do with it. The setup is read off the main scheme card, in the language your cards are in.',
  briefingGather: 'Gather',
  mainSchemeDeck: 'Main scheme deck',
  encounterDeck: 'Encounter deck',
  schemeSetupTitle: 'Main scheme setup',
  damageOnVillain: 'Damage on the villain',
  threatOnScheme: 'Threat on the main scheme',
  schemeForPlayer: (n) => `Player ${n}`,
  tapToCorrect: 'Tap the time to correct it',
  correctTheClock: 'Time played, as minutes',
  keepScreenOn: 'Keep the screen on',
  briefingNoSetup: 'This scenario prints no setup on its main scheme; it is in the rules insert or the campaign book.',
  howDidItEnd: 'How did it end?',
  timePlayedLabel: 'Time played',

  startCampaign: 'Start a campaign',
  campaign: 'Campaign',
  campaignName: 'Call it',
  campaignRoster: 'Who is playing',
  campaignRosterNote:
    'The roster is fixed for the whole campaign. Each player keeps their own credits, scars and upgrades from the first scenario to the last, so this is asked once and never again.',
  campaignWip: 'This campaign is marked unfinished by whoever wrote it. Parts of it may be missing.',
  campaignsUnavailable: 'The campaigns could not be loaded.',
  campaignDifficulty: (id) => (id === 'expert' ? 'Expert' : 'Standard'),
  campaignComplete: 'Campaign complete',
  campaignLost: 'The campaign is lost',
  campaignSummary: (played, won) => `${played} scenarios played, ${won} won.`,
  campaignBetween: 'Between scenarios',
  campaignContinue: 'Continue',
  campaignOpen: 'Open this campaign',
  campaignStatusNotStarted: 'Not started',
  campaignStatusInProgress: 'In progress',
  campaignStatusWon: 'Won',
  campaignStatusLost: 'Lost',
  campaignStatusConceded: 'Conceded',
  campaignDetails: 'Details',
  campaignHideDetails: 'Hide details',
  campaignResultsLabel: (won, played) => `${played} games played, ${won} won`,
  actionTaken: 'Done.',
  promptUnsupported: (type) =>
    `This build cannot ask this question yet (${type}). Record it by hand on the campaign sheet.`,

  campaignPreSetup: 'Pre-setup',
  campaignSetupLabel: 'Campaign setup',
  campaignInformation: 'Subordinates and play tips',
  campaignVillainDeck: 'Villain deck',
  campaignMainScheme: 'Main scheme deck',
  campaignImReady: "I'm ready",
  campaignNotReady: "I'm not ready yet",
  campaignChooseOne: 'Tap the one you want to keep',
  campaignNothingRecorded: 'Nothing recorded',
  campaignNobody: 'Nobody',

  campaignQuestionsTitle: 'A few questions',
  campaignNoQuestions: 'Nothing to record for this outcome.',
  campaignAnswerRequired:
    'A required choice is still open. The campaign expects it, and later scenarios assume it was made.',
  campaignCardListHint: 'Card names separated by commas.',
  campaignNoDeckCards: 'No deck cards available for this run.',
  campaignValidate: 'Validate',
  campaignValidating: 'Recording...',
  campaignBravo: 'Bravo!',
  campaignDefeatRecorded: 'Defeat recorded',
  campaignGoToNext: (name) => `Go to ${name}`,
  campaignRetry: 'I can beat you! (retry)',
  campaignContinueLeavesOpen:
    'Moving on does not fail this scenario. It stays open, against the same villain, for whenever you come back to it.',
  campaignTakeABreak: 'Take a break',
  campaignStopCampaign: 'Stop the campaign',
  campaignChooseScenario: 'Which scenario next?',
  campaignDoneShopping: 'Done shopping',
  campaignWhoIsBuying: 'Who is buying?',
  campaignFinishedMessage:
    'The last villain is down and the campaign is yours. Everything below is what it took.',
  campaignFinishedCleanup:
    'Before your next game, take the campaign cards back out of your decks.',

  campaignEnvironmentTitle: 'The villains push two places.',
  campaignEnvironmentLast: 'One place left. It takes the hit twice.',
  campaignPushed: 'pushed one step',
  campaignPushedTwice: 'alone in the pile, pushed two steps',

  market: 'Market',
  creditsLeft: (n) => `${n} credits`,
  ownedBy: (name) => `taken by ${name}`,
  buy: 'Buy',
  refund: 'Give back',
  yes: 'Yes',
  saveResult: 'Save the game',
  backToGame: 'Back to the game',
  cancel: 'Cancel',
  syncTitle: 'Keeping this browser in step',
  syncSwitch: 'Sync this browser with the account',
  liveOn: 'Changes from your other devices arrive here as they happen.',
  liveOffline: 'Offline. Anything you record is kept and sent when you are back.',
  syncForkExplain:
    'The same deck was edited on two devices and neither version is safe to discard, so you get both: the second is renamed rather than overwritten. Nothing was duplicated, and nothing was lost.',
  syncSwitchNote:
    'Signing in only said who you are. This is what moves your collection, decks, games and campaigns between your devices.',
  autoSyncSwitch: 'Sync on its own',
  autoSyncNote:
    'Every change made here goes to the account within a couple of seconds, and changes made elsewhere arrive here as they happen. This choice stays on this browser and is never carried to your other devices, so each one decides for itself.',
  autoSyncScenario: 'When a scenario ends, in a campaign or not',
  autoSyncCampaign: 'When a campaign ends',
  autoSyncBreak: 'When you put a game away for a long break',
  autoSyncDeck: 'When a deck is built or imported',
  autoSyncCollection: 'When your collection changes',
  autoSyncFavourite: 'When a card is added to your favourites',
  syncStaging: 'Reading the account. Nothing on this browser has been touched yet.',
  syncWorking: 'Working\u2026',
  syncOn: 'In step with the account.',
  syncNow: 'Sync now',
  syncStopped:
    'A batch did not get through, so the rest is still waiting. It will be sent again next time \u2014 nothing was applied twice.',
  syncDone: (pulled, pushed) =>
    pulled === 0 && pushed === 0 ?
      'Already in step. Nothing to move.'
    : `Brought down ${pulled} and sent up ${pushed}.`,
  syncAdoptTitle: 'Before anything moves',
  syncAdoptNothing: 'This browser and the account already hold the same thing. Nothing to merge.',
  syncAdoptKeeps:
    'Nothing here is deleted. What this browser has and the account does not is uploaded; what the account has and this browser does not comes down.',
  syncAdoptGo: 'Merge them',
  syncArriving: (n) => `${n} coming down`,
  syncUploading: (n) => `${n} going up`,
  syncMerging: (n) => `${n} to reconcile`,
  syncForkNote: (n) =>
    n === 1 ?
      'One deck was edited in both places. Nothing reconciles two card lists, so the account\u2019s copy keeps its name and yours is kept beside it as a second deck.'
    : `${n} decks were edited in both places. Nothing reconciles two card lists, so the account\u2019s copies keep their names and yours are kept beside them.`,
  collectionName: (collection) =>
    ({
      settings: 'Settings',
      owned_packs: 'Packs',
      excluded_modular_sets: 'Excluded modular sets',
      excluded_scenarios: 'Excluded scenarios',
      favourite_cards: 'Favourite cards',
      favourite_plays: 'Starred games',
      ratings: 'Difficulty ratings',
      saved_decks: 'Decks',
      campaign_runs: 'Campaigns',
      campaign_events: 'Campaign log',
      plays: 'Games',
      randomizer_history: 'Randomiser draws',
    })[collection] ?? collection,
  playWon: 'won',
  playLost: 'lost',
  bggUsername: 'BoardGameGeek username',
  bggNote:
    'Kept in this browser only: never synced, never written to a backup. With a username alone, games are logged on BGG’s own site by hand; with the password too, they can be sent from here.',
  bggOpenProfile: 'Open this profile on BoardGameGeek',
  bggTitle: 'BoardGameGeek',
  bggMenuSubtitle: 'Sync with BGG',
  bggAboutTitle: 'About BoardGameGeek',
  bggAbout:
    'BoardGameGeek keeps a log of the games you play. Connected, Thwart can send each finished game there: the result and scenario, the heroes and aspects, the day and the times, your notes. BGG has no way to do this without your password, so it goes through the thwart.app server, which signs in, posts the play and keeps nothing — not the password, not the username, not the session. Both stay in this browser only: never synced, never in a backup.',
  bggConnectedAs: (username) => `Connected to “${username}”`,
  bggNotConnected: 'Not connected',
  bggSignInTitle: 'Sign in to BGG',
  bggPassword: 'BoardGameGeek password',
  bggPasswordWarning:
    'This is your BoardGameGeek password, not your Thwart one. It is kept in this browser and sent, through thwart.app, only when a game is posted.',
  bggNeedsAccount:
    'Sending games needs a Thwart account signed in on this browser: the relay is only open to one. Without it you can still note your BGG username and log games on their site by hand.',
  bggRelayOff:
    'This server does not relay games to BoardGameGeek. You can still note your username and log games on their site by hand.',
  bggConnect: 'Connect',
  bggVerifying: 'Checking with BoardGameGeek…',
  bggLoginOk: 'Login is correct',
  bggSyncTitle: 'Sync with BGG',
  bggModeOff: 'Off',
  bggModeAsk: 'Ask',
  bggModeAlways: 'Always',
  bggModeOffDetail: 'Games are not sent. The connection is kept, unused.',
  bggModeAskDetail: 'After each game, a button offers to send it.',
  bggModeAlwaysDetail: 'Every finished game is sent as soon as it is recorded.',
  bggSynced: (n) => (n === 1 ? '1 game synced with BGG' : `${n} games synced with BGG`),
  bggDisconnect: 'Disconnect',
  bggDisconnectConfirm: 'Forget the BoardGameGeek connection on this browser?',
  bggSend: 'Send to BGG',
  bggSending: 'Sending to BGG…',
  bggSent: 'Sent to BGG',
  bggSendFailed: (reason) => `Not sent to BGG: ${reason}`,
  bggError: (code) =>
    ({
      bgg_bad_credentials: 'BoardGameGeek did not accept that username and password.',
      bgg_rejected: 'BoardGameGeek refused the request. Its play form may have changed.',
      bgg_unreachable: 'BoardGameGeek could not be reached. Try again later.',
      bgg_disabled: 'this server does not relay games to BoardGameGeek.',
      rate_limited: 'too many attempts. Wait a little and try again.',
      unauthorized: 'you have been signed out of Thwart. Sign in again.',
      offline: 'the server could not be reached. Check your connection.',
    })[code] ?? 'something went wrong on the server. Try again.',
  bggLogPlay: 'Log on BGG',
  bggFollowUp: 'The form is open in another tab.',
  bggCopy: 'Copy the details',
  bggCopied: 'Copied',
  bggMark: 'Mark as logged',
  bggUnmark: 'Not logged on BGG after all',
  bggLogged: 'on BGG',
  playEdit: 'Edit',
  playAgain: 'Play again',
  playAgainModularNote:
    'Same scenario, difficulty and heroes as that game. The modular sets are not recorded on a game, so choose them again.',
  favouritePlayAdd: 'Star this game',
  favouritePlayRemove: 'Remove the star',
  historyFavouritesOnly: 'Starred only',
  favouriteGames: 'Starred games',
  favouriteGamesNote: 'Games you starred in the history, to lay out again in one tap.',
  extraModulars: 'Extra modular sets',
  extrasShortLocked: (scenario, available, extras) =>
    `Your collection has ${available} modular set${available === 1 ? '' : 's'} for ${scenario}; it cannot add ${extras}.`,
  extrasShortAll: (extras) =>
    `No scenario in your collection can take ${extras} extra modular set${extras === 1 ? '' : 's'}.`,
  extrasShortSome: (scenarios, extras) =>
    `${scenarios} scenario${scenarios === 1 ? '' : 's'} cannot take ${extras} extra${extras === 1 ? '' : 's'} and ${scenarios === 1 ? 'is' : 'are'} left out of this draw.`,
  playThisDraw: 'Play this game',
  modularSearch: 'Find a modular set\u2026',
  modularSelectedCount: (n) => (n === 1 ? '1 modular set' : `${n} modular sets`),
  modularRequired: 'Required by the scenario',
  modularShowAll: 'Show sets I do not own',
  modularNotOwned: 'Not in your collection',
  modularRemove: 'Remove',
  difficultyWord: (score) =>
    ['Effortless', 'Easy', 'Fair', 'Hard', 'Brutal', 'Impossible'][score] ?? String(score),
  ratingTitle: 'How hard was it?',
  ratingCampaignTitle: 'How hard was the campaign, all told?',
  ratingOptional: 'Optional. Your rating is yours to see; the community average appears once a subject has five.',
  ratingYours: 'Your rating',
  ratingClear: 'Clear',
  ratingCommunity: (mean, count) => `${mean.toFixed(1)} \u00b7 ${count} rating${count === 1 ? '' : 's'}`,
  ratingCountOnly: (count) => `${count} rating${count === 1 ? '' : 's'} so far`,
  ratingRejected: (count) =>
    count === 1
      ? 'One rating was refused by the server: it was for a game the server does not have. It has been removed.'
      : `${count} ratings were refused by the server: they were for games the server does not have. They have been removed.`,
  ratingRefreshing: 'Updating\u2026',
  playEditSave: 'Save the correction',
  playWhen: 'Played on',
  playResult: 'Result',
  playDelete: 'Delete',
  playDeleteConfirm: 'Delete this game? It does not come back.',
  deckDeleteConfirm: (name) => `Delete \u201c${name}\u201d? It does not come back.`,
  deckDeleteYes: 'Delete it',
  deckNotFound: 'No deck here. It may have been deleted, or it lives in another browser or account.',
  deckBackToShelf: 'Back to the decks',
  deckSearchIn: 'Search this deck\u2026',
  viewList: 'List',
  viewGrid: 'Grid',
  deckHeroLabel: 'Hero',
  deckNemesis: 'Nemesis set',
  deckNemesisNote: 'Shuffled into the encounter deck when the hero\u2019s obligation is drawn. Not part of the deck, and not chosen.',
  playDeleteYes: 'Delete it',
  campaignsInProgress: 'In progress',
  campaignsFinished: 'Finished',
  campaignDelete: 'Delete this campaign',
  campaignDeleteConfirm: (plays, events) => {
    const log = `its log of ${events} ${events === 1 ? 'entry' : 'entries'}`;
    if (plays === 0) {
      return `This removes the campaign and ${log}. It does not come back.`;
    }
    const games =
      plays === 1 ? 'the game recorded against it' : `the ${plays} games recorded against it`;
    const leave = plays === 1 ? 'it leaves' : 'they leave';
    return `This removes the campaign, ${log}, and ${games} \u2014 so ${leave} your statistics too. It does not come back.`;
  },
  campaignDeleteYes: 'Delete it',
  campaignGames: 'Games recorded',
  statsGames: 'Every game',
  statsGamesNote:
    'Deleting a game removes it from every device and from these numbers. It stays here as a deleted row so the removal can reach your phone, and so it can be undone.',
  statsShowMore: (remaining) => `Show ${remaining} more`,
  statsShowFewer: 'Show fewer',
  statAverageGame: 'Average game',
  statLongestGame: 'Longest game',
  statCurrentStreak: 'Current streak',
  statBestStreak: 'Best streak',
  statCampaignGames: 'In a campaign',
  statSoloGroup: 'Solo / group',
  statsFilter: 'Filter the tables',
  statsSort: 'Sort',
  statsMeasure: 'Measure',
  sortMostPlayed: 'Most played',
  sortAlphabetical: 'A to Z',
  sortBestRate: 'Best rate',
  sortWorstRate: 'Worst rate',
  measureWinRate: 'Win rate',
  measureLossRate: 'Loss rate',
  measureShare: 'Share of games',
  favourite: 'Add to favourites',
  unfavourite: 'Remove from favourites',
  backupTitle: 'Backup file',
  backupIntro:
    'The same file the Android app reads and writes. Until there is an account to sync with, this is how data moves between your phone and this browser.',
  backupImport: 'Import a backup…',
  backupExport: 'Export a backup',
  backupAboutToImport: 'This file contains:',
  backupMerge: 'Merge into what is here',
  backupReplace: 'Replace everything',
  backupMergeHint:
    'Merging keeps what is already in this browser and lets the file win where both hold the same thing. Importing the same file twice changes nothing.',
  backupCarriedNote:
    'Decks, plays and campaigns are stored and will be in anything you export, but this site cannot display them yet.',
  backupPhotosNote: (count) =>
    `${count} photographs are named in this file. The images themselves live on the phone and are not part of the bundle.`,
  backupNotJson: 'That file is not JSON.',
  backupUnreadable: 'That file is not a Thwart backup.',
  backupImportFailed: 'The import failed and nothing was changed.',
  backupImported: (packs, favourites) =>
    `Imported. ${packs} packs and ${favourites} favourites are now in this browser.`,
  countPacks: (n) => `${n} packs`,
  countFavourites: (n) => `${n} favourite cards`,
  countDecks: (n) => `${n} decks`,
  countPlays: (n) => `${n} recorded plays`,
  countCampaigns: (n) => `${n} campaigns`,
};
