import type { Strings } from '../i18n';

/**
 * The French strings. Its own module, loaded on demand (lib/i18n `loadStrings`),
 * so the bundle a visitor downloads carries one language and not both; the
 * other arrives in idle time, in case they switch.
 */
export const fr: Strings = {
  appName: 'Thwart',
  tagline: 'Cartes, collection, decks et statistiques pour Marvel Champions',
  seo: {
    homeTitle: 'Thwart — compagnon Marvel Champions : cartes, collection, decks, campagnes',
    homeDescription:
      'Un compagnon gratuit pour Marvel Champions : Le Jeu de Cartes. Cartes, collection, decks, parties au hasard et campagnes. Hors ligne, sans compte.',
    cardTitle: 'Carte Marvel Champions — Thwart',
    cardsTitle: 'Recherche de cartes Marvel Champions, toutes les cartes en français et en anglais — Thwart',
    cardsDescription:
      'Cherchez toutes les cartes Marvel Champions par nom, texte, trait, type, affinité ou extension, en français ou en anglais, avec vos cartes possédées marquées. Gratuit, hors ligne.',
    cardTitleNamed: (name) => `${name} — carte Marvel Champions — Thwart`,
    cardDescription:
      'Texte, caractéristiques, set et extension de la carte pour Marvel Champions : Le Jeu de Cartes, d’après MarvelCDB, en français ou en anglais.',
    collectionTitle: 'Suivi de collection Marvel Champions — Thwart',
    collectionDescription:
      'Cochez les extensions Marvel Champions que vous possédez et voyez quelles cartes, héros et scénarios vous avez. Conservé sur votre appareil, exportable, et synchronisé entre appareils avec un compte facultatif.',
    randomizerTitle: 'Générateur de partie aléatoire Marvel Champions — Thwart',
    randomizerDescription:
      'Tirez une partie de Marvel Champions au hasard parmi les extensions que vous possédez : scénario, sets modulaires, héros et aspects, à la difficulté de votre choix.',
    versusTitle: 'Mode compétitif Marvel Champions — Thwart',
    versusDescription:
      'Le mode compétitif à deux boîtes de Marvel Champions, mis en place à partir des boîtes que vous possédez.',
    playTitle: 'Suivi de partie Marvel Champions — Thwart',
    playDescription:
      'Mettez en place une partie de Marvel Champions, suivez les points de vie du vilain et la menace de la manigance, et enregistrez le résultat avec vos héros, aspects et sets modulaires.',
    campaignsTitle: 'Suivi de campagne Marvel Champions — Thwart',
    campaignsDescription:
      'Jouez les neuf campagnes de Marvel Champions — Crâne Rouge, Titan Fou, Convoitise Galactique, Genèse des Mutants, NeXt Evolution, Ère d’Apocalypse, Agents du S.H.I.E.L.D., Sinistres Motivations, Peur de Rien — avec chaque étape de mise en place, tirage et embranchement gérés pour vous.',
    rulesTitle: 'Référence des règles Marvel Champions — Thwart',
    rulesDescription: 'La référence des règles de Marvel Champions : Le Jeu de Cartes, avec recherche.',
    decksTitle: 'Constructeur de decks Marvel Champions — Thwart',
      decksDescription:
        'Construisez et v\u00e9rifiez des decks Marvel Champions avec les cartes que vous poss\u00e9dez, importez depuis MarvelCDB, rangez-les en dossiers.',
    draftTitle: 'Draft Marvel Champions \u2014 Thwart',
    draftDescription:
      'Draftez un deck Marvel Champions avec les cartes que vous poss\u00e9dez\u00a0: une identit\u00e9, une affinit\u00e9, puis une carte \u00e0 la fois parmi une main tir\u00e9e au hasard. De un \u00e0 quatre joueurs sur un appareil.',
    historyTitle: 'Historique des parties — Thwart',
    historyDescription: 'Toutes vos parties de Marvel Champions, filtrées par héros, scénario, résultat ou campagne.',
    achievementsTitle: 'Succès — Thwart',
    achievementsDescription: 'Quels héros ont battu quels scénarios, et les succès que vos parties ont gagnés. Lu dans votre historique, gardé sur votre appareil.',
    statsTitle: 'Statistiques — Thwart',
    statsDescription: 'Vos taux de victoire à Marvel Champions par héros, aspect, scénario, difficulté et nombre de joueurs.',
    accountTitle: 'Compte — Thwart',
    accountDescription: 'Un compte facultatif pour synchroniser Thwart entre vos appareils et l’application Android.',
    bggTitle: 'BoardGameGeek — Thwart',
    bggDescription: 'Envoyez vos parties de Marvel Champions sur BoardGameGeek depuis Thwart.',
    notFoundTitle: 'Page introuvable — Thwart',
    notFoundDescription: 'Il n’y a rien à cette adresse.',
  },
  notFoundTitle: 'Il n’y a rien ici',
  notFoundBody: 'Cette adresse ne correspond à aucune page de Thwart. Le lien est peut-être ancien, ou mal tapé.',
  notFoundHome: 'Aller à l’accueil',
  homeIntroTitle: 'Thwart, un compagnon pour Marvel Champions',
  homeIntro:
    'Toutes les cartes de Marvel Champions : Le Jeu de Cartes, en français ou en anglais, à chercher ci-dessous. Cochez les extensions que vous possédez, et le site sait quels decks vous pouvez construire, quelles parties vous pouvez tirer et quelles campagnes vous pouvez jouer.',
  homeIntroNote:
    'Gratuit, hors ligne, rien à installer et sans compte. Aussi sur Android. Non officiel : données des cartes de MarvelCDB ; Marvel Champions appartient à Fantasy Flight Games et Marvel.',
  home: {
    title: 'Thwart, le compagnon Marvel Champions',
    lead:
      'Toutes les cartes de Marvel Champions : Le Jeu de Cartes en français ou en anglais, votre collection, un constructeur de decks qui connaît les règles, un générateur de partie aléatoire, un draft, les neuf campagnes avec leur mise en place et leur suivi, et l’historique et les statistiques de vos parties. Gratuit, hors ligne, dans le navigateur et sur Android.',
    readyToPlay: (name) => `Prêt à jouer, ${name}`,
    accountTitle: 'Gardez vos parties, où que vous jouiez',
    accountBody:
      'Sans compte, tout vit dans ce seul navigateur : effacer ses données, ou changer d’appareil, perd votre collection, vos decks, vos campagnes et vos parties. Un compte les garde en sûreté et synchronisées entre navigateurs et l’application Android, et enregistre vos parties sur BoardGameGeek si vous le souhaitez.',
    accountNote: 'Tout fonctionne sans, sur cet appareil. Une adresse, un mot de passe, rien d’autre.',
    signIn: 'Se connecter ou créer un compte',
    whereTo: 'Où aller',
    cardsDetail: 'Toutes les cartes, par nom, texte, trait, type, affinité ou extension.',
    rulesDetail: 'La référence des règles, pour la question qui arrive en pleine partie.',
    collectionDetail: 'Cochez les extensions que vous possédez ; le reste du site suit.',
    playDetail: 'Une campagne, votre propre partie, une partie aléatoire ou un draft, avec le chrono et le suivi de la rencontre.',
    randomCard: 'Une carte au hasard',
    randomCardDetail: 'Une carte parmi tout le jeu, pour le plaisir. Rechargez pour une autre.',
    historyDetail: 'Toutes vos parties enregistrées, avec leur méchant, leurs héros, leurs tours et leur durée.',
    statsDetail: 'Taux de victoire par héros, affinité, scénario et nombre de joueurs.',
    elsewhere: 'Ailleurs',
    patreon: 'Soutenir Thwart sur Patreon',
    patreonDetail: 'Le site et l’application sont gratuits et le restent ; un café fait tourner le serveur.',
    android: 'Thwart pour Android',
    androidDetail: 'Le même compagnon en application, sur GitHub. Votre compte synchronise les deux.',
    whatsNew: 'Nouveautés',
    earlier: 'Changements précédents',
  },
  achievements: {
    title: 'Succès',
    intro: 'Ce que vous avez battu, avec qui, et quoi jouer ensuite. Tout ici est lu dans l’historique de vos parties.',
    completionOwned: (won, cells) => `${won} / ${cells} cases gagnées dans votre collection`,
    pairsTitle: 'Complétion',
    pairsOwned: (won, cells) => `${won} / ${cells} héros × scénarios battus dans votre collection`,
    namedTitle: 'Succès',
    namedCount: (unlocked, total) => `${unlocked} / ${total} débloqués`,
    completionGlobal: (won, cells) => `${won} / ${cells} dans tout le jeu`,
    rate: (percent) => `${percent} %`,
    gridTitle: 'Héros × scénarios',
    legendNever: 'Jamais joué',
    legendPlayed: 'Joué, pas gagné',
    legendWon: 'Gagné',
    cell: (hero, scenario, attempts, wins) => `${hero} contre ${scenario} : ${attempts} jouées, ${wins} gagnées`,
    bestLevel: (level) => `Meilleure victoire : ${level}`,
    filterHeroPack: 'Extension du héros',
    filterScenarioPack: 'Extension du scénario',
    filterAspect: 'Affinité',
    filterMinDifficulty: 'Difficulté minimale',
    filterAnySeat: 'Compter tous les héros à la table',
    filterOwnerSeat: 'Compter ma place seulement',
    filterShowLosses: 'Afficher les défaites comme jouées',
    filterAll: 'Toutes',
    filterEveryHero: 'Afficher tous les héros',
    heroWon: (won, total) => `${won} / ${total} scénarios battus dans votre collection`,
    cellShort: (attempts, wins) => `${wins} gagnée${wins > 1 ? 's' : ''} sur ${attempts}`,
    listTitle: 'Succès nommés',
    unlocked: 'Débloqué',
    locked: 'Verrouillé',
    unavailable: 'Absent de votre collection',
    unavailableHint: 'La progression est conservée ; posséder l’extension la fait compter.',
    progress: (current, target) => `${current} / ${target}`,
    unlockedOn: (date) => `Débloqué le ${date}`,
    count: (unlocked, total) => `${unlocked} / ${total} débloqués`,
    recentTitle: 'Derniers succès',
    recentEmpty: 'Rien encore. Jouez, et revenez.',
    toastOne: (title) => `Succès débloqué : ${title}`,
    toastMany: (count) => `${count} succès débloqués`,
    toastOpen: 'Voir',
    unavailableFile: 'Le fichier des succès est plus récent que ce que cette version comprend. Mettez à jour pour les voir.',
    hubProgress: (won, cells) => `${won} / ${cells}`,
    stripCount: (unlocked, total) => `${unlocked}/${total} succès débloqués`,
    lockedTitle: 'Succès verrouillés',
    seeMine: 'Voir mes succès',
    hubLabel: 'Succès',
    statsLink: 'Voir les succès',
    category: (c) => ({ coverage: 'Couverture', difficulty: 'Difficulté', volume: 'Volume', table: 'Nombre de joueurs', campaign: 'Campagnes', mode: 'Modes Thwart' })[c] ?? c,
    tier: (t) => ({ bronze: 'Bronze', silver: 'Argent', gold: 'Or', platinum: 'Platine' })[t] ?? t,
    level: (l) => ({ unknown: 'Difficulté inconnue', standard: 'Standard', expert: 'Expert' })[l] ?? l,
  },
  achievement: {
    beat_every_scenario_core: { title: 'Boîte de base terminée', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_trors: { title: 'Crâne Rouge terminé', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_gmw: { title: 'Galaxie terminée', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_mts: { title: 'Titan terminé', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_sm: { title: 'Sinistres terminés', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_mut_gen: { title: 'Genèse terminée', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_next_evol: { title: 'Évolution terminée', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_aoa: { title: 'Apocalypse terminée', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_aos: { title: 'S.H.I.E.L.D. terminé', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario_fne: { title: 'La ville du Caïd terminée', description: 'Battez chaque scénario de {pack}.' },
    beat_every_scenario: { title: 'Plus rien debout', description: 'Battez chaque scénario du jeu.' },
    win_with_every_hero_core: { title: 'Les cinq d’origine', description: 'Gagnez avec chaque héros de {pack}.' },
    win_with_every_hero: { title: 'Tous rassemblés', description: 'Gagnez avec chaque héros du jeu.' },
    win_all_aspects: { title: 'Quatre façons de gagner', description: 'Gagnez avec chacune des quatre affinités.' },
    rhino_all_aspects: { title: 'Rhino, quatre fois', description: 'Battez Rhino avec chacune des quatre affinités.' },
    first_expert_win: { title: 'Expert', description: 'Gagnez une partie en Expert.' },
    beat_every_scenario_core_expert: { title: 'Boîte de base, à la dure', description: 'Battez chaque scénario de {pack} en Expert.' },
    beat_every_scenario_expert: { title: 'Sans pitié', description: 'Battez chaque scénario du jeu en Expert.' },
    plays_count: { title: 'Habitué', description: 'Jouez {n} parties.' },
    wins_count: { title: 'Vainqueur', description: 'Gagnez {n} parties.' },
    heroes_played: { title: 'Large distribution', description: 'Jouez {n} héros différents.' },
    distinct_days: { title: 'Soirées jeu', description: 'Jouez {n} jours différents.' },
    true_solo_win: { title: 'Vrai solo', description: 'Gagnez avec un seul héros à la table.' },
    two_player_win: { title: 'Duo', description: 'Gagnez une partie à deux.' },
    three_player_win: { title: 'Trio', description: 'Gagnez une partie à trois.' },
    four_player_win: { title: 'Table pleine', description: 'Gagnez une partie à quatre.' },
    four_player_four_aspects: { title: 'Un de chaque', description: 'Gagnez une partie à quatre avec quatre affinités différentes.' },
    finish_campaign: { title: 'La longue route', description: 'Terminez une campagne.' },
    finish_campaign_no_defeat: { title: 'Sans faute', description: 'Terminez une campagne sans perdre une partie.' },
    finish_campaign_expert: { title: 'Vétéran de campagne', description: 'Terminez une campagne en Expert.' },
    draft_win: { title: 'Drafté pour gagner', description: 'Gagnez avec un deck construit au draft.' },
  },
  searchPlaceholder: 'Rechercher des cartes…',
  searchLabel: 'Rechercher des cartes',
  interfaceLanguage: 'Interface',
  cardLanguage: 'Cartes',
  theme: 'Thème',
  themeSystem: 'Système',
  themeLight: 'Clair',
  themeDark: 'Sombre',
  trackEncounter: 'Suivre le vilain et la machination',
  trackEncounterNote:
    'Affiche les compteurs de points de vie et de menace pendant la partie. Désactivez-les si vous comptez sur la table.',
  playLocation: 'Où vous jouez',
  playLocationNote:
    'Rempli sur chaque partie enregistrée. Retenu depuis la dernière que vous avez saisie.',
  allTypes: 'Tous les types',
  allFactions: 'Toutes les factions',
  allPacks: 'Tous les paquets',
  allTraits: 'Tous les traits',
  costFrom: 'Coût de',
  costTo: 'à',
  ownedOnly: 'Seulement ce que je possède',
  favouritesOnly: 'Seulement les favorites',
  clearFilters: (active) => `Effacer ${active} filtre${active === 1 ? '' : 's'}`,
  loading: 'Chargement de la base de cartes…',
  loadError: 'Impossible de charger la base de cartes.',
  pageLoadError: 'Impossible de charger cette page. Rechargez pour obtenir la version actuelle du site.',
  retry: 'Réessayer',
  noResults: 'Aucune carte ne correspond.',
  noResultsHint: 'Essayez moins de mots, ou effacez les filtres.',
  resultCount: (shown: number, total: number) =>
    shown === total ? `${total} cartes` : `${shown} cartes sur ${total}`,
  showMore: (n) => `Afficher ${n} de plus`,
  back: 'Retour à la recherche',
  cardNotFound: "Cette carte n'est pas dans la base.",
  traits: 'Traits',
  illustrator: 'Illustrateur',
  pack: 'Paquet',
  inYourCollection: 'Dans votre collection',
  ownedNone: 'Aucun',
  ownedCopies: (n) => (n === 1 ? '1 exemplaire' : `${n} exemplaires`),
  viewOnMarvelCdb: 'Voir sur MarvelCDB',
  resources: 'Ressources',
  cost: 'Coût',
  unique: 'Unique',
  dataFrom: 'Données des cartes :',
  dataUpdated: 'Mise à jour',
  legal:
    'Le texte et les images des cartes Marvel Champions appartiennent à Fantasy Flight Games et à Marvel. Projet de fan non officiel.',
  footerPatreon: 'Soutenir Thwart sur Patreon',
  footerAndroid: 'Thwart pour Android',
  footerSource: 'Code source sur GitHub',
  footerReport: 'Signaler un bug ou m’écrire',
  statHealth: 'Points de vie',
  statHandSize: 'Taille de main',
  statAttack: 'Attaque',
  statThwart: 'Neutralisation',
  statDefense: 'Défense',
  statRecover: 'Récupération',
  statScheme: 'Complot',
  statBoost: 'Bonus',
  statThreat: 'Menace',

  navRules: 'Règles',
  rulesTitle: 'Guide des règles',
  rulesSearchHint: 'Rechercher dans les règles',
  rulesNoResults: 'Aucune règle ne correspond à votre recherche.',
  rulesLoadError: 'Impossible de charger le guide des règles.',
  rulesLoading: 'Chargement du guide des règles…',
  rulesCount: (shown, total) =>
    shown === total
      ? `${total} entrées`
      : `${shown} ${shown === 1 ? 'entrée' : 'entrées'} sur ${total}`,
  rulesCreditBefore: 'Compilé par',
  rulesCreditAfter: (licence) =>
    `et publié sous ${licence}, ce qui est la seule raison pour laquelle il peut figurer ici. Non officiel, sans lien avec Fantasy Flight Games.`,
  navCampaigns: 'Campagnes',
  campaignsTitle: 'Campagnes',
  campaignsEmpty: 'Aucune campagne ici.',
  campaignsEmptyHint:
    "Importez une sauvegarde de l'application Android sur la page Collection et vos campagnes apparaîtront.",
  campaignProgress: (done, total) =>
    done === 1 ? `1 scénario battu sur ${total}` : `${done} scénarios battus sur ${total}`,
  campaignConceded: 'abandonnée',
  campaignFinished: 'terminée',
  campaignPlays: (n) =>
    n === 1
      ? '1 partie enregistrée appartient à cette campagne.'
      : `${n} parties enregistrées appartiennent à cette campagne.`,
  campaignUnread: (n) =>
    n === 1
      ? "1 événement du journal de cette campagne n'est pas lu par cette page."
      : `${n} événements du journal de cette campagne ne sont pas lus par cette page.`,
  attempts: (n) => `${n} tentatives`,
  navPlay: 'Ma propre partie',
  navHistory: 'Historique',
  statsRecord: 'Bilan',
  statsSeeHistory: (games) =>
    `Voir les ${games} parties dans l'historique`,
  loadingGames: 'Lecture de vos parties…',
  historyTitle: 'Historique',
  historyFilters: "Restreindre l'historique",
  historyFrom: 'Du',
  historyTo: 'Au',
  historyAny: 'Toutes',
  historyResult: 'Résultat',
  historyInACampaign: 'En campagne',
  historyOutsideACampaign: 'Hors campagne',
  historyClear: 'Effacer les filtres',
  historyCount: (shown, total) =>
    shown === total ? `${total} parties` : `${shown} parties sur ${total}`,
  historyEmpty: 'Aucune partie enregistrée pour le moment.',
  historyEmptyHint:
    "Enregistrez-en une depuis Ma propre partie, ou importez une sauvegarde de l'application Android sur la page Ma collection. Tout ce que vous jouez apparaît ici.",
  historyNoMatches: 'Aucune partie ne correspond à ces filtres.',
  historyNoMatchesHint: 'Élargissez la période, ou effacez-les pour recommencer.',
  historyRunEmpty: 'Aucun scénario enregistré pour cette campagne.',
  historyDeleteConfirm:
    'Ceci retire la partie de tous vos appareils et de vos statistiques. Elle est conservée comme ligne supprimée, pour que la suppression circule et puisse être annulée.',
  navStats: 'Stats',
  playTitle: 'Ma propre partie',
  playSetupNote: 'Choisissez tout vous-même. Le chronomètre tourne pendant la partie.',
  choose: 'Choisir…',
  standardSetWith: 'Set Standard joué avec',
  seats: 'Decks & nombre de joueurs',
  addDeck: 'Ajouter un deck',
  noSeatsYet: 'Ajoutez au moins un deck.',
  noDecksForPlay:
    "Un joueur est un deck, il n'y a donc rien à ajouter pour le moment. Importez-en un sur la page Decks et il apparaîtra ici.",
  modularChooseNote:
    'Ce que vous avez réellement mélangé. Seuls les sets modulaires des paquets que vous possédez sont listés.',
  startGame: 'Commencer la partie',
  pauseClock: 'Mettre en pause',
  resumeClock: 'Reprendre',
  recordResult: 'Enregistrer le résultat',
  location: 'Lieu de la partie',
  victoryPoints: 'Points de victoire',
  notes: 'Notes',
  won: 'Victoire',
  lost: 'Défaite',
  discardGame: 'Ignorer cette partie',
  discardNote:
    "Abandonner n'enregistre rien : aucune partie dans votre historique ni dans vos statistiques.",
  playRecorded: 'Enregistrée.',
  playAnother: 'Rejouer',
  statsTitle: 'Statistiques',
  statsEmpty: 'Aucune partie enregistrée pour le moment.',
  statsEmptyHint:
    "Enregistrez-en une depuis Ma propre partie, ou importez une sauvegarde de l'application Android sur la page Collection.",
  statsNote:
    'Compté par siège : une partie à quatre crédite les quatre héros et non le premier seulement.',
  winRateOf: (won, total) =>
    `${won} victoire${won === 1 ? '' : 's'} sur ${total} partie${total === 1 ? '' : 's'}`,
  timePlayed: (formatted) => `${formatted} de jeu`,
  wonOf: (won, played) => `${won}/${played}`,
  byHero: 'Par héros',
  byAspect: 'Par aspect',
  byHeroAspect: 'Par héros et aspect',
  byScenario: 'Par scénario',
  byDifficulty: 'Par difficulté',
  byPlayerCount: 'Par nombre de joueurs',
  playerBucket: (bucket) =>
    ({
      players_1: 'Solo',
      players_2: 'Deux joueurs ou deux mains',
      players_3: 'Trois joueurs',
      players_4: 'Quatre joueurs',
      players_5plus: 'Plus de quatre',
    })[bucket] ?? bucket,
  navDecks: 'Decks',
  deckName: 'Nom du deck',
  deckSave: 'Enregistrer',
  deckContents: 'Dans le deck',
  deckAddCards: 'Ajouter des cartes',
  deckEmpty: 'Encore vide. Cherchez \u00e0 droite et appuyez sur le plus.',
  deckHeroCards: 'Cartes du h\u00e9ros',
  deckTabDeck: 'Deck',
  deckTabPool: 'Cartes',
  deckProblems: (n) => (n === 1 ? '1 probl\u00e8me' : `${n} probl\u00e8mes`),
  factionLabel: 'Aspect',
  typeLabel: 'Type',
  sortLabel: 'Tri',
  sortByName: 'par nom',
  sortByCost: 'par co\u00fbt',
  deckHeroCardsFixed: 'Dans chaque deck de ce h\u00e9ros, au nombre imprim\u00e9.',
  deckAddHeroCards: 'Ajouter les cartes du h\u00e9ros',
  deckOwnedOnlyEmpty: 'Votre collection est vide, rien ne peut correspondre. Cochez vos paquets sur la page Collection, ou d\u00e9cochez ceci pour voir toutes les cartes.',
  deckStats: 'De quoi il est fait',
  deckCopy: 'Copier en texte',
  deckCopied: 'Copi\u00e9',
  deckEdit: 'Modifier',
  deckNew: 'Construire un deck',
  deckPickHero: 'H\u00e9ros',
  deckPickAspect: 'Aspect',
  deckCreate: 'Commencer',
  deckCardCount: (total, min, max) => `${total} cartes (${min}\u2013${max})`,
  deckAverageCost: (average) => `Co\u00fbt moyen ${average}`,
  deckResources: (physical, mental, energy, wild) =>
    `Ressources : ${physical} physique, ${mental} mental, ${energy} \u00e9nergie, ${wild} joker`,
  deckTooFew: (actual, required) => `Seulement ${actual} cartes. Un deck en demande ${required}.`,
  deckTooMany: (actual, allowed) => `${actual} cartes. Un deck en accepte ${allowed} au plus.`,
  deckWrongAspects: (actual, required) =>
    `${actual} aspect${actual === 1 ? '' : 's'} choisi${actual === 1 ? '' : 's'} ; ce h\u00e9ros en prend ${required}.`,
  deckOffAspect: (card) => `${card} n\u2019est pas dans un aspect que ce deck peut prendre.`,
  deckOverLimit: (card, quantity, limit) =>
    `${quantity} exemplaires de ${card}, et la limite est de ${limit}.`,
  deckDuplicateUnique: (card) =>
    `${card} est unique : un seul exemplaire, le h\u00e9ros compris.`,
  deckMissingRequired: (card, required, actual) =>
    `${card} fait partie des cartes du h\u00e9ros : ${required} attendue${required === 1 ? '' : 's'}, ${actual} dans le deck.`,
  deckUnbalanced: (counts) =>
    `Les aspects choisis doivent contribuer \u00e9galement (${counts}).`,
  decksTitle: 'Decks',
  decksOf: (handle) => `Decks de ${handle}`,
  decksOfThisBrowser: 'Decks de ce navigateur',
  decksCount: (n) => (n === 1 ? '1 deck' : `${n} decks`),
  foldersCount: (n) => (n === 1 ? '1 dossier' : `${n} dossiers`),
  cardsInDecks: (n) => (n === 1 ? '1 carte en deck' : `${n} cartes en deck`),
  folderLabel: 'Dossier',
  folderNone: 'Sans dossier',
  folderNew: 'Nouveau dossier',
  folderNamePlaceholder: 'Nom du dossier',
  folderCreate: 'Cr\u00e9er',
  folderRename: 'Renommer',
  folderDelete: 'Supprimer le dossier',
  folderDeleteConfirm: (name) => `Supprimer le dossier \u00ab\u00a0${name}\u00a0\u00bb ? Ses decks restent.`,
  deckLegal: 'Ce deck est légal.',
  deckLegalShort: 'légal',
  deckIllegalShort: 'non légal',
  draft: {
    title: 'Draft',
    intro:
      'Un deck construit un choix \u00e0 la fois, comme un draft de Magic\u00a0: une identit\u00e9, une affinit\u00e9, puis une main de cartes tir\u00e9es au hasard dans votre collection, une gard\u00e9e, et on recommence. De un \u00e0 quatre joueurs sur cet appareil, chacun son tour\u00a0; chaque deck finit l\u00e9gal et arrive sur l\u2019\u00e9tag\u00e8re.',
    noHeroes: 'Aucune identit\u00e9 dans votre collection. Cochez d\u2019abord les extensions que vous poss\u00e9dez sur la page Collection.',
    shelf: (heroes, cards) => `${heroes} identités et ${cards} cartes sur l’étagère, depuis votre collection.`,
    stepIdentity: 'Une identité, tirée ou choisie',
    stepAspects: 'Ses affinités et la taille du deck',
    stepPacks: 'Des paquets construits depuis votre collection : ouvrez-en un, gardez une carte, jusqu’à ce que le deck soit plein',
    resume: 'Un draft est en cours.',
    players: 'Joueurs',
    synergy: 'Exclure les cartes sans synergie avec l\u2019identit\u00e9',
    synergyDetail: 'Les cartes qui exigent un trait que l\u2019identit\u00e9 n\u2019a pas ne sont pas propos\u00e9es. Les cartes sans condition le sont toujours.',
    identityMode: 'Identit\u00e9s',
    modeRandom: 'Al\u00e9atoire',
    modeRandomOfFive: 'Al\u00e9atoire parmi 5',
    modeChoice: 'Au choix',
    offerSize: 'Cartes propos\u00e9es \u00e0 chaque choix',
    offerSizeDetail: 'Plus de choix, un deck plus r\u00e9gulier\u00a0; moins, plus de surprises.',
    begin: 'Choisir les identit\u00e9s',
    playerN: (n) => `Joueur ${n}`,
    identityTitle: (n) => `Joueur ${n}\u00a0: identit\u00e9`,
    identityDrawn: 'Tir\u00e9e pour vous',
    drawAgain: 'Retirer',
    chooseIdentity: 'Choisissez une identit\u00e9',
    chooseOfFive: 'Choisissez parmi les cinq',
    searchHeroes: 'Chercher une identit\u00e9\u2026',
    takenBy: (n) => `Prise par le joueur ${n}`,
    aspectsTitle: 'Affinit\u00e9',
    aspectsImposed: 'Cette identit\u00e9 joue les quatre affinit\u00e9s\u00a0; sa r\u00e8gle d\u00e9cide.',
    aspectsPickN: (n) => `Choisissez-en ${n}`,
    aspectsDraw: 'Au hasard',
    deckSize: 'Taille du deck',
    deckSizeDetail: (cards, signature, picks) => `Cartes\u00a0: ${cards}. De l\u2019identit\u00e9\u00a0: ${signature}. Choix\u00a0: ${picks}.`,
    next: 'Suivant',
    startDraft: 'Lancer le draft',
    shortfallTitle: 'Pas assez de cartes en stock',
    shortfallLine: (player, needed, available) => `Joueur ${player}\u00a0: cartes n\u00e9cessaires, ${needed}\u00a0; en stock avec ces affinit\u00e9s, ${available}.`,
    shortfallHint: 'R\u00e9duisez une taille de deck, choisissez d\u2019autres affinit\u00e9s, ou d\u00e9sactivez l\u2019option synergie.',
    picksMade: (made, total) => `${made} / ${total} choix faits`,
    picksLabel: 'choix faits',
    round: (n) => `Paquet ${n} \u00b7 choisissez une carte`,
    packsSealed: (n) => (n === 1 ? '1 paquet encore scellé' : `${n} paquets encore scellés`),
    yourDeck: 'Votre deck',
    identity: 'Identit\u00e9',
    handOver: (n) => `Au tour du joueur ${n}`,
    handOverDetail: 'Passez l\u2019appareil. Le choix pr\u00e9c\u00e9dent est hors de vue.',
    reveal: 'Voir ma main',
    nothingLeft: 'Plus rien de l\u00e9gal en stock pour ce deck. Il s\u2019arr\u00eate ici, en dessous de sa taille.',
    stopHere: 'S\u2019arr\u00eater ici',
    abandon: 'Abandonner le draft',
    abandonConfirm: 'Abandonner ce draft\u00a0? Les choix faits jusqu\u2019ici sont perdus.',
    finishTitle: 'Nommez les decks',
    finishDetail: 'Chaque deck repasse par la v\u00e9rification habituelle, puis tous sont enregistr\u00e9s d\u2019un coup.',
    deckName: 'Nom du deck',
    finish: 'Fin du draft',
    saved: (n) => (n === 1 ? 'Le deck est sur l\u2019\u00e9tag\u00e8re.' : `${n} decks sont sur l\u2019\u00e9tag\u00e8re.`),
    illegal: (name, problems) => `${name} n\u2019est pas l\u00e9gal (${problems} probl\u00e8me${problems === 1 ? '' : 's'}) \u2014 c\u2019est un bug, et rien n\u2019a \u00e9t\u00e9 enregistr\u00e9. Les d\u00e9tails sont dans la console du navigateur.`,
    short: (name, cards, size) => `${name} s\u2019est arr\u00eat\u00e9 \u00e0 ${cards} cartes sur ${size} et ne peut pas \u00eatre enregistr\u00e9. Les autres, oui.`,
  },
  synergyIssue: (names) =>
    names.length === 1
      ? `Problème de synergie : la carte ${names[0]} n’a pas de synergie avec l’identité`
      : `Problème de synergie : la carte ${names[0]} (et ${names.slice(1).join(', ')}) n’a pas de synergie avec l’identité`,
  synergyHideIncompatible: 'Masquer les cartes sans synergie avec l’identité',
  deckIllegal: (n) =>
    n === 1 ? '1 problème dans ce deck :' : `${n} problèmes dans ce deck :`,
  deckLegalityUnknown:
    "La carte du héros n'est pas dans la base, ce deck ne peut donc pas être vérifié.",
  deckComposition: 'Composition',
  deckByType: 'Par type',
  deckByAspect: 'Par aspect',
  averageCost: (avg) => `Coût moyen ${avg}`,
  resourceName: (key) =>
    ({ physical: 'physique', mental: 'mental', energy: 'énergie', wild: 'joker' })[key] ?? key,
  problemAspectCount: (chosen, expected) =>
    `Ce héros prend ${expected} ${expected === 1 ? 'aspect' : 'aspects'} ; le deck en annonce ${chosen}.`,
  problemTooFew: (actual, minimum) => `${actual} cartes, moins que le minimum de ${minimum}.`,
  problemTooMany: (actual, maximum) => `${actual} cartes, plus que le maximum de ${maximum}.`,
  problemRequired: (card, required, actual) =>
    `${card} : les cartes du héros ne sont pas optionnelles (${required} requises, ${actual} présentes).`,
  problemOffAspect: (card, faction) =>
    `${card} est ${faction}, un aspect que ce deck n'a pas pris.`,
  problemCopyLimit: (title, total, limit) =>
    `${total} exemplaires de ${title} ; la limite est de ${limit}.`,
  problemDuplicateUnique: (title, total) =>
    `${total} exemplaires de ${title}, qui est unique.`,
  problemUnbalanced: (counts) =>
    `Les aspects de ce héros doivent contribuer à parts égales : ${counts}.`,
  importDeck: 'Importer depuis MarvelCDB',
  importDeckNote:
    "Collez le lien d'une decklist, ou simplement son numéro. Le deck est enregistré dans ce navigateur, avec la même clé que l'application Android : l'importer des deux côtés donne un seul deck et non deux.",
  importAction: 'Importer',
  importing: 'Import en cours…',
  deckImportNotFound:
    "Aucun deck à cette adresse. Les decklists publiées fonctionnent toujours ; un deck personnel ne fonctionne que si son auteur l'a partagé.",
  deckImportNetwork: 'Impossible de joindre MarvelCDB.',
  noDecks: 'Aucun deck pour le moment.',
  removeDeck: 'Supprimer',
  cardCount: (n) => `${n} cartes`,
  deckMissing: (cards, packs) =>
    `${cards} cartes de ce deck ne sont pas dans votre collection, réparties dans ${packs} paquets que vous ne possédez pas.`,
  deckBuildable: 'Vous possédez toutes les cartes de ce deck.',
  deckUnknownCards: (n) =>
    `${n} cartes de ce deck ne sont pas encore dans la base. MarvelCDB saisit les nouvelles cartes au rythme des bénévoles.`,
  notOwned: 'non possédée',
  deckLocaleNote: (locale) =>
    `Les noms de cartes sont affichés en ${locale === 'fr' ? 'français' : 'anglais'}, selon la langue des cartes choisie ci-dessus.`,
  navRandomizer: 'Partie al\u00e9atoire',
  navDraft: 'Draft',
  navVersus: 'Comp\u00e9titif',
  versusTitle: 'Partie comp\u00e9titive',
  versusIntro:
    'Chaque \u00e9quipe construit un sc\u00e9nario et le donne \u00e0 l\u2019autre : ce qu\u2019une \u00e9quipe affronte ici, c\u2019est le leader et les manigances de l\u2019adversaire.',
  versusNeedsBox:
    'Le mode comp\u00e9titif demande une bo\u00eete qui le propose. Ajoutez-en une \u00e0 votre collection et il r\u00e9appara\u00eetra.',
  versusBox: 'Bo\u00eete',
  versusFaces: 'Cette \u00e9quipe affronte :',
  versusLeader: 'Leader',
  versusStageOne: 'Manigance principale, stade 1',
  versusStageTwo: 'Manigance principale, stade 2',
  versusPlayers: 'Joueurs dans cette \u00e9quipe',
  versusStart: 'Commencer la partie',
  versusEndRound: 'Finir le round sur les deux tableaux',
  versusRound: (round) => `Round ${round}`,
  versusWhoWon: 'Qui a gagn\u00e9 ?',
  versusTie: '\u00c9galit\u00e9',
  versusAgain: 'Une autre partie',
  versusTiebreakTitle: 'D\u00e9partages, dans l\u2019ordre',
  versusTiebreaks: [
    'L\u2019\u00e9quipe dont le deck manigance principale adverse n\u2019a pas d\u00e9pass\u00e9 le stade 1B.',
    'L\u2019\u00e9quipe avec le moins de sbires et de manigances annexes dans sa zone.',
    'L\u2019\u00e9quipe avec le moins de menace sur la manigance principale de sa zone.',
    'L\u2019\u00e9quipe dont les identit\u00e9s ont le plus de points de vie restants.',
    'L\u2019\u00e9quipe avec le moins d\u2019attachements sur son leader.',
  ],
  filters: 'Filtres',
  filtersNote:
    "Ces filtres ne valent que pour cette session et ne sont pas enregistrés. Ce que vous possédez se règle sur la page Collection ; ici, c'est ce dont vous avez envie ce soir.",
  aspects: 'Aspects',
  excludeBeaten: (n) =>
    n === 0 ? 'Ignorer les scénarios déjà battus' : `Ignorer les scénarios déjà battus (${n})`,
  resetFilters: 'Tout réautoriser',
  savedDraws: 'Résultats enregistrés',
  beatenNote:
    "Cochez un scénario une fois battu, et le filtre ci-dessus pourra l'ignorer.",
  randomizerTitle: 'Partie aléatoire',
  randomizerNoCollection:
    "Cochez d'abord les paquets que vous possédez sur la page Collection. Seul ce que vous pouvez réellement mettre sur la table est proposé.",
  randomizerNotEnough: (players) =>
    `Votre collection ne suffit pas pour ${players} joueurs. Ajoutez des paquets, ou jouez à moins.`,
  poolNote: (scenarios, heroes, modulars) =>
    `Parmi ${scenarios} scénarios, ${heroes} héros et ${modulars} sets modulaires.`,
  players: 'Joueurs',
  roll: 'Lancer',
  reroll: 'Relancer',
  lockField: 'Conserver au prochain lancer',
  scenario: 'Scénario',
  villain: 'Méchant',
  difficultyLabel: 'Difficulté',
  difficulty: (id) =>
    ({
      STANDARD_I: 'Standard I',
      STANDARD_II: 'Standard II',
      STANDARD_III: 'Standard III',
      EXPERT_I: 'Expert I',
      EXPERT_II: 'Expert II',
    })[id] ?? id,
  heroes: 'Héros',
  aspect: (id) =>
    ({
      aggression: 'Agressivité',
      justice: 'Justice',
      leadership: 'Commandement',
      protection: 'Protection',
      pool: 'Pool',
    })[id] ?? id,
  required: 'obligatoire',
  noModularSets: 'Ce scénario ne prend aucun set modulaire.',
  saveToHistory: 'Enregistrer ce résultat',
  savedToHistory: 'Enregistré',
  wave: (n) => `Vague ${n}`,
  waveUnknown: 'Non classés',
  navHome: 'Accueil',
  navCards: 'Cartes',
  navCollection: 'Ma collection',
  navPlayShort: 'Jouer',
  navMore: 'Plus',
  hubStart: 'Commencer une partie',
  hubRandomDetail:
    'Laissez l’application choisir un scénario, des héros et des affinités parmi ce que vous possédez.',
  hubOwnDetail: 'Choisissez tout vous-même. L’application chronomètre la partie.',
  hubCampaignDetail: 'Démarrez une campagne, ou ouvrez-en une terminée.',
  hubDraftDetail: 'Construisez un deck un choix à la fois, à partir de cartes tirées de votre collection.',
  hubPaused: 'Une partie vous attend',
  settingsGroupedPlay: 'Un seul onglet Jouer',
  settingsGroupedPlayHint:
    'Regroupe la partie aléatoire, votre propre partie, le draft, les campagnes et le compétitif derrière un seul onglet Jouer, comme l’application Android.',
  navMoreTitle: 'Tout le reste',
  settingsTitle: 'Paramètres',
  close: 'Fermer',

  accountTitle: 'Compte',
  accountSignIn: 'Se connecter',
  accountCreate: 'Cr\u00e9er un compte',
  accountForgot: 'Mot de passe oubli\u00e9',
  accountRecoverAction: 'R\u00e9initialiser le mot de passe',
  accountHandle: 'Pseudo',
  accountPassword: 'Mot de passe',
  savedOnServer: 'Sur le serveur',
  savedLocalOnly: 'Sur cet appareil seulement',
  registeredCheckMail: (address) =>
    `Le compte existe, et il est désactivé tant que vous n'avez pas ouvert le lien envoyé à ${address}. Regardez dans les indésirables s'il n'y est pas.`,
  registeredThenSignIn:
    "S'inscrire ne vous connecte pas. Ouvrez le lien, puis connectez-vous ici — sur cet appareil et sur ceux que vous voulez garder synchronisés.",
  accountYourData: 'Vos données',
  accountExport: 'Télécharger mes données',
  accountExporting: 'Préparation…',
  accountExportNote:
    "Tout ce que ce compte contient sur le serveur, dans le même fichier que l'application lit et écrit. À vous de le garder, de l'emporter ailleurs ou de le vérifier.",
  accountDeleteTitle: 'Supprimer ce compte',
  accountDelete: 'Supprimer mon compte',
  accountDeleteNote:
    "Supprime le compte et tout ce qui y est synchronisé : votre adresse, vos decks, vos parties, vos campagnes et votre collection. C'est définitif, et ce n'est pas la même chose que se déconnecter. Ce qui est sur cet appareil y reste.",
  accountDeleteConfirm:
    "Ceci supprime le compte et tout ce qui est sur le serveur. Aucun retour en arrière. Saisissez votre mot de passe pour confirmer.",
  accountDeleteYes: 'Supprimer définitivement',
  verifyTitle: 'Confirmation de votre adresse',
  verifyWorking: 'Un instant.',
  verifyDone: (handle) => `Confirmée. Le compte ${handle} fonctionne désormais.`,
  verifyDoneHint:
    'Connectez-vous sur les appareils que vous voulez garder synchronisés. Ouvrir un lien ne connecte pas ce navigateur.',
  verifyFailedHint:
    "Un lien ne sert qu'une fois et expire au bout d'une semaine. Demandez-en un nouveau depuis l'écran du compte.",
  verifyGoToAccount: 'Aller au compte',
  verifyPendingTitle: 'Confirmez votre adresse',
  verifyPendingBody: (address) =>
    `Le compte est désactivé tant que vous n'avez pas ouvert le lien envoyé à ${address}. Rien ne se synchronise d'ici là. S'il n'est jamais arrivé, regardez dans les indésirables puis demandez-en un autre.`,
  verifyResend: 'Renvoyer le lien',
  verifyResent: "C'est parti. Cela peut prendre une minute.",
  verifyAlready: 'Cette adresse est déjà confirmée.',
  accountNewPassword: 'Nouveau mot de passe',
  accountRecoveryCode: 'Code de r\u00e9cup\u00e9ration',
  accountDeviceName: 'Nom de ce navigateur',
  accountDeviceNameNote:
    'Affich\u00e9 dans la liste de vos appareils, pour les distinguer et pouvoir en d\u00e9connecter un.',
  accountManage: 'Gérer le compte',
  accountClosed:
    'Ce serveur n’accepte pas de nouveaux comptes pour l’instant. Si vous en avez déjà un, connectez-vous — et si vous avez perdu le mot de passe, le code de récupération fonctionne toujours.',
  navSignIn: 'Connexion',
  accountEmail: 'Adresse e-mail',
  accountEmailNote:
    'C\u2019est avec elle que vous vous connectez. Elle ne sert \u00e0 rien d\u2019autre : aucune lettre d\u2019information, aucune mesure d\u2019audience, et elle n\u2019est transmise \u00e0 personne.',
  accountHandleNote:
    'Le nom affich\u00e9 sur votre compte. Vous vous connectez avec votre adresse, pas avec lui.',
  accountPasswordRule:
    'Au moins 12 caract\u00e8res. Une phrase dont vous vous souviendrez vaut mieux qu\u2019un mot de passe court plein de symboles. Il ne peut contenir ni votre pseudo ni votre adresse.',
  accountRecoveryNote:
    'Vous recevez aussi un code de r\u00e9cup\u00e9ration, une seule fois. Tant que ce serveur ne peut pas envoyer d\u2019e-mail, ce code est le seul moyen de revenir si vous oubliez votre mot de passe : gardez-le.',
  accountSignedInAs: 'Connect\u00e9 en tant que',
  accountDeviceIs: (name) => `Ce navigateur est enregistr\u00e9 sous \u00ab\u00a0${name}\u00a0\u00bb.`,
  accountDevices: 'Appareils',
  accountThisDevice: 'celui-ci',
  accountLeaving: 'D\u00e9connexion',
  accountSignOut: 'Se d\u00e9connecter',
  accountSignOutKeeps:
    'Tout ce qui est sur ce navigateur reste exactement o\u00f9 c\u2019est. Se d\u00e9connecter oublie le compte, pas votre collection, vos decks, vos parties ni vos campagnes.',
  accountWhy: '\u00c0 quoi sert un compte',
  accountWhyBody:
    'Un seul endroit pour votre collection, vos decks, vos parties et vos campagnes, afin que les m\u00eames donn\u00e9es soient sur votre t\u00e9l\u00e9phone et dans ce navigateur. En attendant, le fichier de sauvegarde de la page Collection est la fa\u00e7on de les d\u00e9placer.',
  accountPrivacy:
    'Le serveur conserve vos enregistrements sans les lire : il ne sait pas ce qu\u2019est une carte. Votre adresse sert \u00e0 vous connecter et \u00e0 rien d\u2019autre. Vous pouvez tout exporter ou supprimer le compte, sans demander la permission \u00e0 personne.',
  accountError: (code) =>
    ({
      invalid_credentials: 'Cette adresse et ce mot de passe ne correspondent \u00e0 aucun compte.',
      email_taken: 'Un compte existe d\u00e9j\u00e0 sur ce serveur avec cette adresse.',
      handle_taken: 'Ce pseudo est d\u00e9j\u00e0 pris sur ce serveur. Essayez-en un autre.',
      invalid_email: 'Cela ne ressemble pas \u00e0 une adresse e-mail.',
      invalid_handle:
        'Un pseudo fait 3 \u00e0 32 caract\u00e8res : lettres, chiffres, point, tiret ou soulignement.',
      weak_password:
        'Ce mot de passe est trop simple. Utilisez au moins 12 caract\u00e8res, sans y mettre votre pseudo ni votre adresse.',
      registration_closed: 'Ce serveur n\u2019accepte pas de nouveaux comptes.',
      invalid_recovery_code: 'Ce code de r\u00e9cup\u00e9ration ne correspond pas \u00e0 ce compte.',
      rate_limited: 'Trop de tentatives. Patientez un peu avant de r\u00e9essayer.',
      server_busy: 'Le serveur est occupé. Réessayez dans un instant.',
      unauthorized: 'Vous avez \u00e9t\u00e9 d\u00e9connect\u00e9. Reconnectez-vous.',
      offline: 'Le serveur est injoignable. V\u00e9rifiez votre connexion.',
    })[code] ?? 'Une erreur est survenue sur le serveur. R\u00e9essayez.',
  recoveryTitle: 'Conservez ce code',
  recoveryIntro:
    'Il n\u2019est affich\u00e9 qu\u2019une seule fois. Ce serveur ne sait pas encore envoyer d\u2019e-mail : jusque-l\u00e0, ce code est le seul moyen de revenir si vous oubliez votre mot de passe. Rangez-le l\u00e0 o\u00f9 vous l\u2019aurez encore dans un an.',
  recoveryDownload: 'Enregistrer dans un fichier',
  recoveryCopy: 'Copier',
  recoverySaved: 'Je l\u2019ai mis en lieu s\u00fbr',
  recoveryDone: 'Termin\u00e9',
  recoveryFileBody: (handle, code) =>
    [
      'Thwart \u2014 code de r\u00e9cup\u00e9ration du compte',
      '',
      `Compte : ${handle}`,
      `Code :   ${code}`,
      '',
      'Ce code r\u00e9initialise le mot de passe de ce compte. Il n\u2019est affich\u00e9',
      'qu\u2019une fois et le serveur n\u2019en garde qu\u2019une empreinte : ce fichier en est',
      'la seule copie. Quiconque le d\u00e9tient peut prendre le compte.',
    ].join('\n'),
  collectionTitle: 'Collection',
  bulkLabel: 'Ajouter d\u2019un coup :',
  bulkAll: 'Tout',
  bulkCore: 'Bo\u00eetes de base',
  bulkHeroes: 'Paquets h\u00e9ros',
  bulkScenarios: 'Paquets sc\u00e9nario',
  bulkCampaigns: 'Bo\u00eetes de campagne',
  bulkClear: 'Vider la collection',
  bulkClearConfirm: (owned) =>
    `Ceci oublie les ${owned} paquets, quantit\u00e9s comprises. C\u2019est d\u00e9finitif.`,
  bulkClearYes: 'Vider',
  collectionIntro:
    "Cochez les paquets que vous possédez. Tout est enregistré dans ce navigateur uniquement : rien n'est envoyé nulle part et il n'y a pas de compte. Utilisez l'export ci-dessous pour emporter vos données ailleurs.",
  collectionOwned: (owned, total) => `${owned} paquets sur ${total} possédés`,
  storageUnavailable:
    "Ce navigateur refuse d'enregistrer les données du site, la collection ne peut donc pas être sauvegardée. Une fenêtre privée ou des données de site bloquées en sont la cause habituelle.",
  copiesOwned: 'Exemplaires possédés',
  showContents: 'Contenu',
  hideContents: 'Masquer',
  contentsHint:
    "Posséder un paquet ne veut pas dire posséder tout ce qu'il contient. Décochez ce qui manque à votre exemplaire et il ne sera plus proposé.",
  scenarios: 'Scénarios',
  modularSets: 'Sets modulaires',

  tracker: 'Méchant et manigance',
  trackerLoading: 'Lecture du scénario…',
  trackerUnavailable: "Ce scénario n'a aucun compteur à tenir.",
  trackerStarred: 'La carte imprime une étoile : saisissez le nombre',
  trackerStarredAcceleration:
    'Cette machination accélère d’un montant étoilé qui dépend du plateau : rien n’est ajouté ici pour elle, déplacez la menace vous-même à la fin du round.',
  trackerNote:
    "Des compteurs, rien de plus. L'application ne sait pas que les drones entrent en jeu ni qu'une icône Crise empêche de contrer : un compteur qui arbitre à moitié se trompe à une table, et les nombres qu'il tient vraiment cessent alors d'être crus.",
  round: (n) => `Tour ${n}`,
  endRound: 'Terminer le tour',
  advanceVillain: 'Retourner le Méchant',
  advanceScheme: 'Faire avancer la manigance',
  whichScheme: 'Laquelle est sur la table',

  longBreak: 'Faire une longue pause ?',
  longBreakIntro:
    "Pour une table qu'il faut débarrasser, ou laisser une semaine. Le chrono s'arrête et la position de chacun est notée. Une partie à la fois : enregistrer remplace celle qui était rangée.",
  longBreakPhase: "Arrêtée pendant",
  phasePlayer: 'La phase des joueurs',
  phaseVillain: 'La phase du Méchant',
  villainStep: (step) =>
    ({
      PLACE_THREAT: 'Placer la Menace sur la manigance principale',
      ACTIVATE_MINIONS: 'Activer les Sbires',
      DEAL_ENCOUNTERS: 'Distribuer les cartes Rencontre',
      REVEAL_ENCOUNTERS: 'Révéler les cartes Rencontre',
      PASS_FIRST_PLAYER: 'Passer le jeton Premier Joueur',
    })[step] ?? step,
  heroLives: 'Points de vie restants',
  villainLifeLeft: 'Points de vie restants du Méchant',
  villainStageLabel: 'Quelle carte Méchant est face visible',
  putAway: 'Faire la pause',
  savePutAway: 'Enregistrer et quitter la table',
  resumeSaved: 'Reprendre la partie',
  discardSaved: 'Jeter',
  savedGame: (scenario, when) => `${scenario}, rangée ${when}`,
  savedGameNote:
    'Reprendre remet les cartes et le chrono là où ils étaient. Le chrono revient arrêté : ressortir le matériel ne compte pas comme du temps de jeu.',

  goToSetup: 'Aller à la mise en place',
  play: 'Jouer',
  backToSetup: 'Modifier la mise en place',
  clockStartsNote: "Le chrono démarre quand vous appuyez sur Jouer, pas avant. Installer une partie prend plusieurs minutes, et les compter faisait paraître chaque partie plus longue qu'elle ne l'était.",
  briefingTitle: 'Préparation',
  briefingIntro: "Ce qu'il faut sortir, et ce que le scénario dit d'en faire. La mise en place est lue sur la carte de manigance principale, dans la langue de vos cartes.",
  briefingGather: 'À sortir',
  mainSchemeDeck: 'Deck manigance principale',
  encounterDeck: 'Deck Rencontre',
  schemeSetupTitle: 'Mise en place de la manigance principale',
  damageOnVillain: 'Dégâts sur le Méchant',
  threatOnScheme: 'Menace sur la manigance principale',
  schemeForPlayer: (n) => `Joueur ${n}`,
  tapToCorrect: 'Touchez le temps pour le corriger',
  correctTheClock: 'Temps de jeu, en minutes',
  keepScreenOn: "Garder l'écran allumé",
  briefingNoSetup: "Ce scénario n'imprime aucune mise en place sur sa manigance principale : elle se trouve dans le livret de règles ou le livret de campagne.",
  howDidItEnd: "Comment cela s'est-il terminé ?",
  timePlayedLabel: 'Temps de jeu',
  roundsPlayed: 'Tours',
  villainStageReached: 'Stade du Méchant atteint',

  startCampaign: 'Commencer une campagne',
  campaign: 'Campagne',
  campaignName: 'Nommez-la',
  campaignRoster: 'Qui joue',
  campaignRosterNote:
    "L'équipe est fixée pour toute la campagne. Chaque joueur garde ses propres crédits, cicatrices et améliorations du premier scénario au dernier : la question est posée une fois et plus jamais.",
  campaignWip: "Cette campagne est marquée inachevée par son auteur. Des passages peuvent manquer.",
  campaignsUnavailable: "Les campagnes n'ont pas pu être chargées.",
  campaignDifficulty: (id) => (id === 'expert' ? 'Expert' : 'Standard'),
  campaignComplete: 'Campagne terminée',
  campaignLost: 'La campagne est perdue',
  campaignSummary: (played, won) => `${played} scénarios joués, ${won} gagnés.`,
  campaignBetween: 'Entre deux scénarios',
  campaignContinue: 'Continuer',
  campaignOpen: 'Ouvrir cette campagne',
  campaignStatusNotStarted: 'Pas commencée',
  campaignStatusInProgress: 'En cours',
  campaignStatusWon: 'Gagnée',
  campaignStatusLost: 'Perdue',
  campaignStatusConceded: 'Abandonnée',
  campaignDetails: 'Détails',
  campaignHideDetails: 'Masquer les détails',
  campaignResultsLabel: (won, played) => `${played} parties jouées, ${won} gagnées`,
  actionTaken: 'Fait.',
  promptUnsupported: (type) =>
    `Cette version ne sait pas encore poser cette question (${type}). Notez-la à la main sur la feuille de campagne.`,

  campaignPreSetup: 'Préparation',
  campaignSetupLabel: 'Mise en place',
  campaignInformation: 'Subordonnés et conseils de jeu',
  campaignVillainDeck: 'Deck du Méchant',
  campaignMainScheme: 'Deck Manigance Principale',
  campaignImReady: 'Je suis prêt',
  campaignNotReady: 'Pas encore prêt',
  campaignChooseOne: 'Touchez celle que vous gardez',
  campaignNothingRecorded: "Rien d'enregistré",
  campaignNobody: 'Personne',

  campaignQuestionsTitle: 'Quelques questions',
  campaignNoQuestions: 'Rien à enregistrer pour ce résultat.',
  campaignAnswerRequired:
    "Un choix obligatoire reste à faire. La campagne l'exige, et les scénarios suivants le supposent acquis.",
  campaignCardListHint: 'Noms de cartes séparés par des virgules.',
  campaignNoDeckCards: 'Aucune carte de deck disponible pour cette partie.',
  campaignValidate: 'Valider',
  campaignValidating: 'Enregistrement...',
  campaignBravo: 'Bravo !',
  campaignDefeatRecorded: 'Défaite enregistrée',
  campaignGoToNext: (name) => `Aller à ${name}`,
  campaignRetry: 'Je peux le battre ! (rejouer)',
  campaignContinueLeavesOpen:
    'Continuer ne fait pas échouer ce scénario. Il reste ouvert, contre le même méchant, pour quand vous y reviendrez.',
  campaignTakeABreak: 'Faire une pause',
  campaignStopCampaign: 'Arrêter la campagne',
  campaignChooseScenario: 'Quel scénario ensuite ?',
  campaignDoneShopping: 'Terminer les achats',
  campaignWhoIsBuying: 'Qui achète ?',
  campaignFinishedMessage:
    "Le dernier Méchant est à terre et la campagne est à vous. Voici ce qu'elle aura coûté.",
  campaignFinishedCleanup:
    'Avant la prochaine partie, retirez les cartes de campagne de vos decks.',

  campaignEnvironmentTitle: 'Les Méchants font progresser deux lieux.',
  campaignEnvironmentLast: 'Un seul lieu restant. Il encaisse deux fois.',
  campaignPushed: "progresse d'une case",
  campaignPushedTwice: 'seul dans la pile, progresse de deux cases',

  market: 'Marché',
  creditsLeft: (n) => `${n} crédits`,
  ownedBy: (name) => `pris par ${name}`,
  buy: 'Acheter',
  refund: 'Rendre',
  yes: 'Oui',
  saveResult: 'Enregistrer la partie',
  backToGame: 'Revenir à la partie',
  cancel: 'Annuler',
  syncTitle: 'Garder ce navigateur \u00e0 jour',
  syncSwitch: 'Synchroniser ce navigateur avec le compte',
  liveOn: 'Les modifications de vos autres appareils arrivent ici en direct.',
  liveOffline: "Hors ligne. Ce que vous enregistrez est conservé et envoyé à votre retour.",
  syncForkExplain:
    "Le même deck a été modifié sur deux appareils et aucune version ne peut être écartée sans risque : vous gardez les deux, la seconde étant renommée plutôt qu'écrasée. Rien n'a été dupliqué, et rien n'a été perdu.",
  syncSwitchNote:
    'Se connecter n\u2019a fait que dire qui vous \u00eates. Ceci d\u00e9place votre collection, vos decks, vos parties et vos campagnes entre vos appareils.',
  autoSyncSwitch: 'Synchroniser tout seul',
  autoSyncNote:
    "Chaque changement fait ici part vers le compte en quelques secondes, et ceux faits ailleurs arrivent ici au fur et à mesure. Ce choix reste sur ce navigateur et n'est jamais transmis à vos autres appareils : chacun décide pour lui-même.",
  autoSyncScenario: "À la fin d'un scénario, en campagne ou non",
  autoSyncCampaign: "À la fin d'une campagne",
  autoSyncBreak: 'Quand vous rangez une partie pour une longue pause',
  autoSyncDeck: "Quand un deck est créé ou importé",
  autoSyncCollection: 'Quand votre collection change',
  autoSyncFavourite: "Quand une carte est ajoutée à vos favoris",
  syncStaging: 'Lecture du compte. Rien n\u2019a encore \u00e9t\u00e9 modifi\u00e9 sur ce navigateur.',
  syncWorking: 'En cours\u2026',
  syncOn: '\u00c0 jour avec le compte.',
  syncNow: 'Synchroniser maintenant',
  syncStopped:
    'Un lot n\u2019est pas pass\u00e9 : le reste attend encore. Il sera renvoy\u00e9 la prochaine fois, et rien n\u2019a \u00e9t\u00e9 appliqu\u00e9 deux fois.',
  syncDone: (pulled, pushed) =>
    pulled === 0 && pushed === 0 ?
      'D\u00e9j\u00e0 \u00e0 jour. Rien \u00e0 d\u00e9placer.'
    : `${pulled} r\u00e9cup\u00e9r\u00e9${pulled === 1 ? '' : 's'}, ${pushed} envoy\u00e9${pushed === 1 ? '' : 's'}.`,
  syncAdoptTitle: 'Avant que quoi que ce soit ne bouge',
  syncAdoptNothing:
    'Ce navigateur et le compte ont d\u00e9j\u00e0 la m\u00eame chose. Rien \u00e0 fusionner.',
  syncAdoptKeeps:
    'Rien n\u2019est supprim\u00e9 ici. Ce que ce navigateur a et pas le compte est envoy\u00e9 ; ce que le compte a et pas ce navigateur est r\u00e9cup\u00e9r\u00e9.',
  syncAdoptGo: 'Fusionner',
  syncArriving: (n) => `${n} \u00e0 r\u00e9cup\u00e9rer`,
  syncUploading: (n) => `${n} \u00e0 envoyer`,
  syncMerging: (n) => `${n} \u00e0 r\u00e9concilier`,
  syncForkNote: (n) =>
    n === 1 ?
      'Un deck a \u00e9t\u00e9 modifi\u00e9 des deux c\u00f4t\u00e9s. Rien ne r\u00e9concilie deux listes de cartes : la copie du compte garde son nom et la v\u00f4tre est conserv\u00e9e \u00e0 c\u00f4t\u00e9, comme un second deck.'
    : `${n} decks ont \u00e9t\u00e9 modifi\u00e9s des deux c\u00f4t\u00e9s. Rien ne r\u00e9concilie deux listes de cartes : les copies du compte gardent leurs noms et les v\u00f4tres sont conserv\u00e9es \u00e0 c\u00f4t\u00e9.`,
  collectionName: (collection) =>
    ({
      settings: 'R\u00e9glages',
      owned_packs: 'Paquets',
      excluded_modular_sets: 'Sets modulaires exclus',
      excluded_scenarios: 'Sc\u00e9narios exclus',
      favourite_cards: 'Cartes favorites',
      favourite_plays: 'Parties favorites',
      ratings: 'Notes de difficult\u00e9',
      saved_decks: 'Decks',
      campaign_runs: 'Campagnes',
      campaign_events: 'Journal de campagne',
      plays: 'Parties',
      randomizer_history: 'Tirages al\u00e9atoires',
    })[collection] ?? collection,
  playWon: 'gagn\u00e9e',
  playLost: 'perdue',
  bggUsername: 'Identifiant BoardGameGeek',
  bggNote:
    'Conservé dans ce navigateur uniquement : jamais synchronisé, jamais écrit dans une sauvegarde. Avec l’identifiant seul, les parties s’enregistrent à la main sur le site de BGG ; avec le mot de passe aussi, elles peuvent être envoyées d’ici.',
  bggOpenProfile: 'Ouvrir ce profil sur BoardGameGeek',
  bggTitle: 'BoardGameGeek',
  bggMenuSubtitle: 'Synchroniser avec BGG',
  bggAboutTitle: 'À propos de BoardGameGeek',
  bggAbout:
    'BoardGameGeek tient le journal des parties que vous jouez. Une fois connecté, Thwart peut y envoyer chaque partie terminée : le résultat et le scénario, les héros et les aspects, le jour et les horaires, vos notes. BGG n’offre aucun moyen de le faire sans votre mot de passe : la partie passe donc par le serveur de thwart.app, qui se connecte, publie la partie et ne garde rien — ni le mot de passe, ni l’identifiant, ni la session. Les deux restent dans ce navigateur uniquement : jamais synchronisés, jamais dans une sauvegarde.',
  bggConnectedAs: (username) => `Connecté à « ${username} »`,
  bggNotConnected: 'Non connecté',
  bggSignInTitle: 'Se connecter à BGG',
  bggPassword: 'Mot de passe BoardGameGeek',
  bggPasswordWarning:
    'C’est votre mot de passe BoardGameGeek, pas celui de Thwart. Il est conservé dans ce navigateur et envoyé, via thwart.app, uniquement au moment de publier une partie.',
  bggNeedsAccount:
    'Envoyer des parties demande un compte Thwart connecté dans ce navigateur : le relais ne s’ouvre qu’à lui. Sans cela, vous pouvez toujours noter votre identifiant BGG et enregistrer vos parties sur leur site à la main.',
  bggRelayOff:
    'Ce serveur ne relaie pas les parties vers BoardGameGeek. Vous pouvez toujours noter votre identifiant et enregistrer vos parties sur leur site à la main.',
  bggConnect: 'Se connecter',
  bggVerifying: 'Vérification auprès de BoardGameGeek…',
  bggLoginOk: 'Identifiants corrects',
  bggSyncTitle: 'Synchronisation avec BGG',
  bggModeOff: 'Jamais',
  bggModeAsk: 'Demander',
  bggModeAlways: 'Toujours',
  bggModeOffDetail: 'Les parties ne sont pas envoyées. La connexion est gardée, sans servir.',
  bggModeAskDetail: 'Après chaque partie, un bouton propose de l’envoyer.',
  bggModeAlwaysDetail: 'Chaque partie terminée est envoyée dès qu’elle est enregistrée.',
  bggSynced: (n) => (n === 1 ? '1 partie synchronisée avec BGG' : `${n} parties synchronisées avec BGG`),
  bggDisconnect: 'Déconnexion',
  bggDisconnectConfirm: 'Oublier la connexion BoardGameGeek sur ce navigateur ?',
  bggSend: 'Envoyer sur BGG',
  bggSending: 'Envoi sur BGG…',
  bggSent: 'Envoyée sur BGG',
  bggSendFailed: (reason) => `Pas envoyée sur BGG : ${reason}`,
  bggError: (code) =>
    ({
      bgg_bad_credentials: 'BoardGameGeek n’a pas accepté cet identifiant et ce mot de passe.',
      bgg_rejected: 'BoardGameGeek a refusé la requête. Son formulaire de partie a peut-être changé.',
      bgg_unreachable: 'BoardGameGeek n’a pas pu être joint. Réessayez plus tard.',
      bgg_disabled: 'ce serveur ne relaie pas les parties vers BoardGameGeek.',
      rate_limited: 'trop de tentatives. Patientez un instant puis réessayez.',
      unauthorized: 'vous avez été déconnecté de Thwart. Reconnectez-vous.',
      offline: 'le serveur n’a pas pu être joint. Vérifiez votre connexion.',
    })[code] ?? 'une erreur est survenue côté serveur. Réessayez.',
  bggLogPlay: 'Enregistrer sur BGG',
  bggFollowUp: "Le formulaire est ouvert dans un autre onglet.",
  bggCopy: 'Copier les détails',
  bggCopied: 'Copié',
  bggMark: 'Marquer comme enregistrée',
  bggUnmark: 'Finalement pas enregistrée sur BGG',
  bggLogged: 'sur BGG',
  playEdit: 'Modifier',
  playAgain: 'Rejouer',
  playAgainModularNote:
    'Même scénario, même difficulté et mêmes héros que cette partie. Les sets modulaires ne sont pas enregistrés sur une partie, choisissez-les à nouveau.',
  favouritePlayAdd: 'Mettre en favori',
  favouritePlayRemove: 'Retirer des favoris',
  historyFavouritesOnly: 'Favoris seulement',
  favouriteGames: 'Parties favorites',
  favouriteGamesNote: 'Les parties que vous avez mises en favori dans l’historique, à remettre en place en un geste.',
  extraModulars: 'Sets modulaires en plus',
  extrasShortLocked: (scenario, available, extras) =>
    `Votre collection a ${available} set${available === 1 ? '' : 's'} modulaire${available === 1 ? '' : 's'} pour ${scenario} : impossible d\u2019en ajouter ${extras}.`,
  extrasShortAll: (extras) =>
    `Aucun sc\u00e9nario de votre collection ne peut prendre ${extras} set${extras === 1 ? '' : 's'} modulaire${extras === 1 ? '' : 's'} en plus.`,
  extrasShortSome: (scenarios, extras) =>
    `${scenarios} sc\u00e9nario${scenarios === 1 ? '' : 's'} ne ${scenarios === 1 ? 'peut' : 'peuvent'} pas prendre ${extras} set${extras === 1 ? '' : 's'} en plus et ${scenarios === 1 ? 'est laiss\u00e9' : 'sont laiss\u00e9s'} de c\u00f4t\u00e9 pour ce tirage.`,
  playThisDraw: 'Jouer cette partie',
  modularSearch: 'Chercher un set modulaire\u2026',
  modularSelectedCount: (n) => (n === 1 ? '1 set modulaire' : `${n} sets modulaires`),
  modularRequired: 'Requis par le sc\u00e9nario',
  modularShowAll: 'Afficher les sets que je ne poss\u00e8de pas',
  modularNotOwned: 'Hors collection',
  modularRemove: 'Retirer',
  difficultyWord: (score) =>
    ['Une formalit\u00e9', 'Facile', '\u00c9quilibr\u00e9', 'Difficile', 'Brutal', 'Impossible'][score] ?? String(score),
  ratingTitle: 'C\u2019\u00e9tait difficile ?',
  ratingCampaignTitle: 'Et la campagne dans son ensemble, difficile ?',
  ratingOptional: 'Facultatif. Votre note reste visible pour vous ; la moyenne de la communaut\u00e9 appara\u00eet \u00e0 partir de cinq notes.',
  ratingYours: 'Votre note',
  ratingClear: 'Effacer',
  ratingCommunity: (mean, count) => `${mean.toFixed(1).replace('.', ',')} \u00b7 ${count} note${count === 1 ? '' : 's'}`,
  ratingCountOnly: (count) => `${count} note${count === 1 ? '' : 's'} pour l\u2019instant`,
  ratingRejected: (count) =>
    count === 1
      ? 'Une note a \u00e9t\u00e9 refus\u00e9e par le serveur : elle portait sur une partie qu\u2019il ne conna\u00eet pas. Elle a \u00e9t\u00e9 retir\u00e9e.'
      : `${count} notes ont \u00e9t\u00e9 refus\u00e9es par le serveur : elles portaient sur des parties qu\u2019il ne conna\u00eet pas. Elles ont \u00e9t\u00e9 retir\u00e9es.`,
  ratingRefreshing: 'Mise \u00e0 jour\u2026',
  playEditSave: 'Enregistrer la correction',
  playWhen: 'Jouée le',
  playResult: 'Résultat',
  playDelete: 'Supprimer',
  playDeleteConfirm: 'Supprimer cette partie ? C\u2019est d\u00e9finitif.',
  deckDeleteConfirm: (name) => `Supprimer \u00ab\u00a0${name}\u00a0\u00bb ? C\u2019est d\u00e9finitif.`,
  deckDeleteYes: 'Supprimer',
  deckNotFound: 'Aucun deck ici. Il a peut-\u00eatre \u00e9t\u00e9 supprim\u00e9, ou il est dans un autre navigateur ou un autre compte.',
  deckBackToShelf: 'Retour aux decks',
  deckSearchIn: 'Chercher dans ce deck\u2026',
  viewList: 'Liste',
  viewGrid: 'Grille',
  deckHeroLabel: 'H\u00e9ros',
  deckNemesis: 'Set n\u00e9m\u00e9sis',
  deckNemesisNote: 'M\u00e9lang\u00e9 dans le deck de rencontre quand l\u2019obligation du h\u00e9ros est pioch\u00e9e. Ni dans le deck, ni choisi.',
  playDeleteYes: 'Supprimer',
  campaignsInProgress: 'En cours',
  campaignsFinished: 'Termin\u00e9es',
  campaignDelete: 'Supprimer cette campagne',
  campaignDeleteConfirm: (plays, events) => {
    const log = `son journal de ${events} entr\u00e9e${events === 1 ? '' : 's'}`;
    if (plays === 0) {
      return `Ceci supprime la campagne et ${log}. C\u2019est d\u00e9finitif.`;
    }
    const games =
      plays === 1 ?
        'la partie enregistr\u00e9e pour elle'
      : `les ${plays} parties enregistr\u00e9es pour elle`;
    const leave = plays === 1 ? 'elle quitte' : 'elles quittent';
    return `Ceci supprime la campagne, ${log} et ${games} \u2014 ${leave} donc aussi vos statistiques. C\u2019est d\u00e9finitif.`;
  },
  campaignDeleteYes: 'Supprimer',
  campaignGames: 'Parties enregistr\u00e9es',
  statsGames: 'Toutes les parties',
  statsGamesNote:
    'Supprimer une partie la retire de tous vos appareils et de ces chiffres. Elle reste ici comme ligne supprimée, pour que la suppression atteigne votre téléphone et puisse être annulée.',
  statsShowMore: (remaining) => `Afficher ${remaining} de plus`,
  statsShowFewer: 'Afficher moins',
  statAverageGame: 'Partie moyenne',
  statLongestGame: 'Partie la plus longue',
  statCurrentStreak: 'Série en cours',
  statBestStreak: 'Meilleure série',
  statCampaignGames: 'En campagne',
  statSoloGroup: 'Solo / groupe',
  statsFilter: 'Filtrer les tableaux',
  statsSort: 'Trier',
  statsMeasure: 'Mesure',
  sortMostPlayed: 'Les plus jouées',
  sortAlphabetical: 'De A à Z',
  sortBestRate: 'Meilleur taux',
  sortWorstRate: 'Pire taux',
  measureWinRate: 'Taux de victoire',
  measureLossRate: 'Taux de défaite',
  measureShare: 'Part des parties',
  favourite: 'Ajouter aux favoris',
  unfavourite: 'Retirer des favoris',
  backupTitle: 'Fichier de sauvegarde',
  backupIntro:
    "Le même fichier que l'application Android lit et écrit. En attendant un compte à synchroniser, c'est ainsi que les données circulent entre votre téléphone et ce navigateur.",
  backupImport: 'Importer une sauvegarde…',
  backupExport: 'Exporter une sauvegarde',
  backupAboutToImport: 'Ce fichier contient :',
  backupMerge: 'Fusionner avec les données présentes',
  backupReplace: 'Tout remplacer',
  backupMergeHint:
    'La fusion conserve ce qui est déjà dans ce navigateur et laisse le fichier gagner en cas de doublon. Importer deux fois le même fichier ne change rien.',
  backupCarriedNote:
    "Les decks, parties et campagnes sont enregistrés et figureront dans vos exports, mais ce site ne sait pas encore les afficher.",
  backupPhotosNote: (count) =>
    `${count} photographies sont nommées dans ce fichier. Les images elles-mêmes restent sur le téléphone et ne font pas partie de la sauvegarde.`,
  backupNotJson: "Ce fichier n'est pas du JSON.",
  backupUnreadable: "Ce fichier n'est pas une sauvegarde Thwart.",
  backupImportFailed: "L'import a échoué et rien n'a été modifié.",
  backupImported: (packs, favourites) =>
    `Import terminé. ${packs} paquets et ${favourites} favoris sont maintenant dans ce navigateur.`,
  countPacks: (n) => `${n} paquets`,
  countFavourites: (n) => `${n} cartes favorites`,
  countDecks: (n) => `${n} decks`,
  countPlays: (n) => `${n} parties enregistrées`,
  countCampaigns: (n) => `${n} campagnes`,
};
