import type { Locale } from '../types';
import type { CampaignState } from './types';
import { scenarioDifficulty } from './encounter';

export interface RedSkullStep { id: string; title: string; lines: readonly string[]; source: string }
export const RED_SKULL_SCENARIOS = {
  s1_crossbones: {villains:['04058','04059','04060'],hp:[12,14],scheme:'04061',start:0,limit:3,page:5},
  s2_absorbing_man: {villains:['04076','04077','04078'],hp:[14,15],scheme:'04079',start:2,limit:12,page:7},
  s3_taskmaster: {villains:['04093','04094','04095'],hp:[13,16],scheme:'04096',start:1,limit:12,page:10},
  s4_zola: {villains:['04109','04110','04111'],hp:[12,14],scheme:'04112',start:0,limit:6,page:12},
  s5_red_skull: {villains:['04125','04126','04127'],hp:[12,16],scheme:'04128',start:0,limit:8,page:15},
} as const;

export function redSkullStartingThreat(state: CampaignState, id: string): number {
  return id==='s5_red_skull' ? Math.max(0,state.counters.delay??0)*(state.difficulty==='expert'?Math.max(1,state.heroes.length):1) : 0;
}

/** Original instructions: mc10 pp. 3, 5, 7, 10, 12, 15, 17 and the printed setup/reveal faces. */
export function redSkullGuide(locale: Locale, state: CampaignState, id: string): readonly RedSkullStep[] {
  const spec=RED_SKULL_SCENARIOS[id as keyof typeof RED_SKULL_SCENARIOS];
  if(!spec)return [];
  const fr=locale==='fr', n=Math.max(1,state.heroes.length), expert=scenarioDifficulty(state,id)==='expert', campaignExpert=state.difficulty==='expert';
  const say=(a:string,b:string)=>fr?a:b;
  const steps:RedSkullStep[]=[];
  const add=(id:string,a:string,b:string,lines:readonly (readonly [string,string])[],source=`mc10 · ${spec.page}`)=>steps.push({id,title:say(a,b),lines:lines.map(([a,b])=>say(a,b)),source});
  const inventory=[...new Set(['tech','conditions','rescued'].flatMap(key=>[...(state.cardLists[key]??[]),...Object.values(state.heroCardLists[key]??{}).flat()]))];
  const reserve=(codes:readonly string[])=>codes.map(code=>`{card:${code}}`).join(', ');
  add('heroes','Installez les joueurs','Set up the players',[
    ['Gardez les identités de la campagne, face alter ego. Choisissez le premier joueur, rassemblez les jetons et les états, puis réglez les PV de départ de chaque identité. Les blessures de campagne seront appliquées plus loin.','Keep the campaign identities, alter-ego side up. Choose the first player, gather tokens and status cards, and set each identity’s starting HP. Campaign damage is applied later.'],
    [inventory.length?`Sortez les cartes de campagne conservées : ${reserve(inventory)}. Réservez les cartes Mise en place pour leur entrée en jeu à l’étape Registre.`:'Aucune récompense de campagne n’est enregistrée.',inventory.length?`Gather retained campaign cards: ${reserve(inventory)}. Reserve Setup cards for their entry into play at the Log step.`:'No campaign reward is recorded.'],
    ...(id==='s5_red_skull'&&(state.cardLists.imprisoned??[]).length?[[`À prévoir : les alliés prisonniers ${reserve(state.cardLists.imprisoned!)} seront retirés à l’étape Registre. Préparez leurs remplaçants, sans résoudre cet effet maintenant.`,`Plan ahead: imprisoned allies ${reserve(state.cardLists.imprisoned!)} will be removed at the Log step. Prepare replacements without resolving that effect now.`] as const]:[]),
    ['Préparez vos decks avec les récompenses conservées. Mettez les obligations des identités de côté pour le deck Rencontre et les sets Némésis en réserve. Ne piochez pas encore.','Prepare your decks with retained rewards. Set identity obligations aside for the encounter deck and nemesis sets aside as reserves. Do not draw yet.'],
    [campaignExpert?'Attribuez à chaque joueur son Set Campagne Experte numéroté de 1 à 4. Conservez les obligations déjà ajoutées dans son deck.':'Les PV sont restaurés entre les scénarios en campagne Standard.',campaignExpert?'Assign each player their Expert Campaign Set numbered 1–4. Retain obligations already added to their deck.':'In a Standard campaign, HP is restored between scenarios.'],
  ],'mc10 · 3, 17 / Rules Reference · setup');
  add('villain','Préparez le méchant','Prepare the villain',[
    [`Posez {card:${spec.villains[expert?1:0]}} (stade ${expert?'II':'I'}) au-dessus de {card:${spec.villains[expert?2:1]}} (stade ${expert?'III':'II'}). Réglez ses PV à ${spec.hp[expert?1:0]*n}. Mettez le stade inutilisé de côté.`,`Place {card:${spec.villains[expert?1:0]}} (stage ${expert?'II':'I'}) above {card:${spec.villains[expert?2:1]}} (stage ${expert?'III':'II'}). Set its HP to ${spec.hp[expert?1:0]*n}. Set the unused stage aside.`],
    ['Attendez l’étape « Révélez le méchant » pour résoudre son effet de révélation, une fois les cartes Rencontre préparées.','Wait until “Reveal the villain” to resolve its reveal effect, once encounter cards are ready.'],
  ]);
  add('deck','Rassemblez les sets Rencontre','Gather encounter sets',[
    ['Prenez tous les exemplaires des sets ci-dessous. Gardez les cartes Méchant et Manigance principale hors du deck ; ajoutez les obligations des identités.','Take every copy from the sets below. Keep villain and main-scheme cards outside the deck; add identity obligations.'],
    [expert?'Ajoutez le set Standard choisi et le set Expert choisi. Expert ne remplace pas Standard.':'Ajoutez le set Standard choisi.',expert?'Add the selected Standard and Expert sets. Expert does not replace Standard.':'Add the selected Standard set.'],
    [id==='s1_crossbones'?'Gardez les quatre Armes expérimentales séparées : elles constituent leur propre deck à l’étape suivante.':'Mélangez le deck Rencontre. Les cartes de campagne conservées seront ajoutées après la préparation du scénario.',id==='s1_crossbones'?'Keep the four Experimental Weapons separate: they form their own deck in the next step.':'Shuffle the encounter deck. Retained campaign cards are added after scenario setup.'],
  ]);
  const setup:Record<string,readonly (readonly [string,string])[]>={
    s1_crossbones:[['Mélangez {card:04072}, {card:04073}, {card:04074} et {card:04075} en un deck face cachée près des manigances. Mélangez le deck Rencontre séparément. Ne révélez pas encore d’arme.','Shuffle {card:04072}, {card:04073}, {card:04074} and {card:04075} into a facedown deck beside the main schemes. Shuffle the encounter deck separately. Do not reveal a weapon yet.'],['Une arme qui entre en jeu rejoint ensuite le circuit du deck Rencontre : lorsqu’elle est défaussée, elle va dans sa défausse. Notez les armes entrées en jeu pour le bilan.','Once a weapon enters play, it becomes part of the encounter deck: discard it into the encounter discard pile. Track weapons that entered play for the result.']],
    s2_absorbing_man:[['Défaussez des cartes Rencontre jusqu’au premier environnement. Mettez-le en jeu, puis remélangez la défausse dans le deck Rencontre. Commencez sans jeton Retard.','Discard encounter cards until the first environment. Put it into play, then shuffle the discard pile back into the encounter deck. Start with no delay counters.'],['Mettre cet environnement en jeu ne déclenche pas Renfort. Absorbing Man acquiert ses traits ; un nouvel environnement remplacera le précédent.','Putting this environment into play does not trigger Surge. Absorbing Man gains its traits; a new environment replaces the old one.']],
    s3_taskmaster:[['Réservez hors jeu les alliés CAPTIF : {card:04097}, {card:04098}, {card:04099} et {card:04100}. Cherchez {card:04154}, mettez-la en jeu avec '+2*n+' menaces, puis mélangez le deck Rencontre.','Set the CAPTIVE allies aside: {card:04097}, {card:04098}, {card:04099} and {card:04100}. Find {card:04154}, put it into play with '+2*n+' threat, then shuffle the encounter deck.'],['Son icône Crise empêche de retirer des menaces de la manigance principale tant qu’elle reste en jeu.','Its Crisis icon prevents removing threat from the main scheme while it remains in play.']],
    s4_zola:[['Cherchez et révélez {card:04122}. Chaque joueur cherche son allié spécifique à son héros dans son deck, sa défausse et sa main, puis le place face cachée dessous et remélange son deck.','Find and reveal {card:04122}. Each player finds their hero-specific ally in their deck, discard pile and hand, places it facedown underneath, then shuffles their deck.'],[`La Prison commence à ${n} menaces, auxquelles s’ajoute la somme des coûts des alliés placés dessous. Chaque joueur met {card:04114} en jeu engagé avec lui : 4 PV et un état Tenace. Mélangez le deck Rencontre.`,`The Prison starts with ${n} threat plus the combined costs of the allies placed underneath. Each player puts {card:04114} into play engaged with them: 4 HP and a Tough status card. Shuffle the encounter deck.`]],
    s5_red_skull:[[`Mettez {card:04139} en jeu avec ${3*n} menaces. Le Crâne Rouge ne peut pas subir de dégâts tant qu’elle reste en jeu. Mettez {card:04130} de côté.`,`Put {card:04139} into play with ${3*n} threat. Red Skull cannot take damage while it remains in play. Set {card:04130} aside.`],['Retirez toutes les autres manigances annexes du deck Rencontre et mélangez-les pour former un deck séparé, avec sa propre défausse. Mélangez le deck Rencontre restant.','Remove all other side schemes from the encounter deck and shuffle them into a separate deck with its own discard pile. Shuffle the remaining encounter deck.'],['Quand le deck des manigances annexes est vide, remélangez sa défausse sans pénalité et sans jeton Accélération.','When the side-scheme deck is empty, reshuffle its discard pile without a penalty or acceleration token.']],
  };
  add('reserve','Résolvez la face 1A','Resolve side 1A',setup[id]!,`mc10 · ${spec.page} / ${spec.scheme}A`);
  add('scheme','Retournez sur 1B et placez la menace','Flip to 1B and place threat',[
    [`Retournez {card:${spec.scheme}a} sur {card:${spec.scheme}b}. Placez ${spec.start*n} menaces de départ ; le seuil est ${spec.limit*n}. La progression imprimée est de ${n} menace(s) par phase du Méchant, avant accélération et effets particuliers.`,`Flip {card:${spec.scheme}a} to {card:${spec.scheme}b}. Place ${spec.start*n} starting threat; the threshold is ${spec.limit*n}. Printed growth is ${n} threat per villain phase, before acceleration and special effects.`],
    [id==='s1_crossbones'?'Gardez {card:04062a} puis {card:04063a} sous le premier stade.':id==='s4_zola'?'Gardez {card:04113a} pour le stade suivant.':id==='s5_red_skull'?'Gardez {card:04129a} pour le stade suivant.':'Ce scénario n’a qu’un stade de manigance principale : atteindre son seuil fait perdre la partie.',id==='s1_crossbones'?'Keep {card:04062a}, then {card:04063a}, beneath the first stage.':id==='s4_zola'?'Keep {card:04113a} for the next stage.':id==='s5_red_skull'?'Keep {card:04129a} for the next stage.':'This scenario has one main-scheme stage: reaching its threshold loses the game.'],
  ],`${spec.scheme}A–B`);
  const reveals:Record<string,readonly [string,string]>={
    s1_crossbones:[`Cherchez {card:04064} dans le deck Rencontre et sa défausse, attachez-la à Crossbones avec ${2*n} munitions, puis mélangez le deck Rencontre.`,`Find {card:04064} in the encounter deck and discard pile, attach it to Crossbones with ${2*n} ammo counters, then shuffle the encounter deck.`],
    s2_absorbing_man:[`Si {card:04092} est déjà en jeu, distribuez une carte Rencontre face cachée à chaque joueur. Sinon, cherchez-la dans le deck Rencontre et sa défausse et révélez-la avec ${3*n} menaces ; mélangez si le deck a été fouillé.`,`If {card:04092} is already in play, deal each player one facedown encounter card. Otherwise find it in the encounter deck and discard pile and reveal it with ${3*n} threat; shuffle if the deck was searched.`],
    s3_taskmaster:['Distribuez une carte Rencontre face cachée à chaque joueur. Elle sera révélée lors de la phase du Méchant.','Deal each player one facedown encounter card. Reveal it during the villain phase.'],
    s4_zola:[`Cherchez {card:04123} dans le deck Rencontre et sa défausse et révélez-la avec ${2*n} menaces. Mélangez le deck Rencontre. Son icône Péril ajoute une carte Rencontre au total distribué à la phase du Méchant.`,`Find {card:04123} in the encounter deck and discard pile and reveal it with ${2*n} threat. Shuffle the encounter deck. Its Hazard icon adds one encounter card to the total dealt during the villain phase.`],
    s5_red_skull:['Distribuez une carte Rencontre face cachée à chaque joueur. Elle sera révélée lors de la phase du Méchant.','Deal each player one facedown encounter card. Reveal it during the villain phase.'],
  };
  add('reveal','Révélez le méchant','Reveal the villain',[[`Révélez {card:${spec.villains[expert?1:0]}} (stade ${expert?'II':'I'}).`,`Reveal {card:${spec.villains[expert?1:0]}} (stage ${expert?'II':'I'}).`],expert?reveals[id]!:['Le stade I n’a pas d’effet de révélation à résoudre.','Stage I has no reveal effect to resolve.'],[id==='s4_zola'?'Zola possède Riposte 1 : un attaquant survivant subit 1 dégât après l’attaque.':'Les capacités permanentes du méchant s’appliquent dès qu’il est en jeu.',id==='s4_zola'?'Zola has Retaliate 1: a surviving attacker takes 1 damage after the attack.':'The villain’s constant abilities apply as soon as it is in play.']],spec.villains[expert?1:0]);
  const experimental=state.cardLists.experimental??[];
  const prisoners=state.cardLists.imprisoned??[];
  const refs=(codes:readonly string[])=>codes.map(c=>`{card:${c}}`).join(', ');
  add('campaign','Appliquez le registre','Apply the campaign log',[
    [id==='s1_crossbones'?'Vos identités sont fixées pour les cinq scénarios.':'Mettez en jeu les cartes Mise en place de vos decks, notamment les récompenses TECH et les améliorations Condition conservées.',id==='s1_crossbones'?'Your identities are fixed for all five scenarios.':'Put Setup cards from your decks into play, including retained TECH rewards and Condition upgrades.'],
    [id==='s1_crossbones'?'Les armes expérimentales restent dans leur deck séparé.':experimental.length?`Ajoutez au deck Rencontre les armes enregistrées : ${refs(experimental)}. Mélangez.`:'Aucune arme expérimentale n’est enregistrée : n’en ajoutez pas au deck Rencontre.',id==='s1_crossbones'?'Experimental Weapons remain in their separate deck.':experimental.length?`Shuffle the recorded weapons into the encounter deck: ${refs(experimental)}.`:'No Experimental Weapons are recorded: add none to the encounter deck.'],
    ...(id==='s5_red_skull'?[[`Ajoutez ${redSkullStartingThreat(state,id)} menaces à la manigance principale : ${state.counters.delay??0} jeton(s) Retard enregistré(s)${campaignExpert?' × '+n+' joueurs':''}. Cette valeur est déjà incluse au lancement d’une nouvelle table.`,`Add ${redSkullStartingThreat(state,id)} threat to the main scheme: ${state.counters.delay??0} recorded delay counter(s)${campaignExpert?' × '+n+' players':''}. This is already included when starting a new table.`] as const,
      [prisoners.length?`Retirez des decks les alliés restés prisonniers : ${refs(prisoners)}. Complétez vos decks si nécessaire pour rester légaux.`:'Aucun allié resté prisonnier n’est enregistré.',prisoners.length?`Remove imprisoned allies from decks: ${refs(prisoners)}. Replenish decks if needed to remain legal.`:'No imprisoned allies are recorded.'] as const,
      ['Conservez la face Condition acquise à la victoire contre Zola : seuls les joueurs en forme héros à cette victoire pouvaient l’améliorer si la Prison avait quitté le jeu. Ne l’améliorez pas une seconde fois pendant cette préparation.','Keep the Condition side earned when defeating Zola: only players in hero form at that victory could improve it if the Prison had left play. Do not improve it again during this setup.'] as const]:[]),
  ]);
  add('health','Reprenez vos PV de campagne','Apply campaign HP',[
    [campaignExpert&&id!=='s1_crossbones'?'Réglez les PV aux valeurs conservées après la dernière victoire. Chaque joueur peut tirer au hasard une obligation encore disponible de son Set Campagne Experte, l’ajouter à son deck et se soigner entièrement. Un joueur éliminé doit payer ce coût pour revenir.':'Commencez aux PV de départ de votre identité.',campaignExpert&&id!=='s1_crossbones'?'Set HP to the values retained after the last victory. Each player may randomly draw an available obligation from their Expert Campaign Set, add it to their deck and heal fully. An eliminated player must pay this cost to rejoin.':'Start at your identity’s starting HP.'],
    [campaignExpert?'Le tirage de l’obligation se fait avec votre set physique. Conservez-la dans votre deck pour la suite de la campagne. Une obligation piochée se met immédiatement en jeu, sans carte de remplacement.':'Les cartes de campagne ajoutées ne comptent pas dans la taille minimale ou maximale du deck.',campaignExpert?'Draw the obligation from your physical set. Keep it in your deck for the rest of the campaign. A drawn obligation enters play immediately, without a replacement card.':'Added campaign cards do not count toward minimum or maximum deck size.'],
  ],'mc10 · 3, 17');
  add('hand','Préparez votre main','Prepare your hand',[
    ['Mélangez vos decks après les ajouts et retraits. Piochez jusqu’à la taille de main de votre alter ego, défaussez les cartes choisies pour le mulligan et complétez la main sans remélanger cette défausse, puis résolvez les capacités Mise en place de vos identités. Ne rejouez pas les étapes déjà résolues à la table.','Shuffle your decks after additions and removals. Draw to your alter-ego hand size, discard chosen mulligan cards and refill without shuffling those discards back, then resolve identity Setup abilities. Do not repeat setup already resolved at the table.'],
    ...(id==='s5_red_skull'&&campaignExpert?[[`Les joueurs enregistrés comme engagés à la victoire contre Zola se distribuent chacun une carte Rencontre supplémentaire : ${state.heroes.filter(h=>state.completedScenarios.some(r=>r.scenarioId==='s4_zola'&&r.victory&&r.answers.perHeroBooleans?.engaged?.[h.id])).map(h=>h.name).join(', ')||'aucun'}.`,`Players recorded as engaged when Zola was defeated each deal themselves an extra encounter card: ${state.heroes.filter(h=>state.completedScenarios.some(r=>r.scenarioId==='s4_zola'&&r.victory&&r.answers.perHeroBooleans?.engaged?.[h.id])).map(h=>h.name).join(', ')||'none'}.`] as const]:[]),
  ],'Rules Reference · setup / mc10 · 15, 17');
  const reminders:Record<string,readonly [string,string]>={
    s1_crossbones:['Crossbones gagne Perçant avec une arme : retirez Tenace avant les dégâts. Chaque nouveau stade de manigance révèle une arme expérimentale ; le troisième seuil fait perdre la partie.','Crossbones gains Piercing with a weapon: discard Tough before damage. Each later main-scheme stage reveals an Experimental Weapon; the third threshold loses the game.'],
    s2_absorbing_man:['Après l’ajout de menace en début de phase du Méchant, ajoutez 1 jeton Retard physique sur la manigance. Notez son total à la victoire pour la suite de la campagne.','After adding threat at the start of the villain phase, add 1 physical delay counter to the scheme. Record its total at victory for the campaign.'],
    s3_taskmaster:['Après le début de phase du Méchant, chaque joueur en forme héros choisit 1 menace ou 1 dégât. Changer en forme héros déclenche aussi Taskmaster : défaussez une carte Rencontre et subissez ses icônes de boost en dégâts.','After the start of the villain phase, each hero-form player chooses 1 threat or 1 damage. Changing to hero form also triggers Taskmaster: discard an encounter card and take damage equal to its boost icons.'],
    s4_zola:['Après l’ajout de menace en début de phase du Méchant, ajoutez 1 jeton Test physique. À 3 ou plus, défaussez jusqu’à un sbire, mettez-le en jeu engagé avec le premier joueur, puis retirez 3 jetons Test.','After adding threat at the start of the villain phase, add 1 physical test counter. At 3 or more, discard until a minion, put it into play engaged with the first player, then remove 3 test counters.'],
    s5_red_skull:['Après l’ajout de menace en début de phase du Méchant, révélez la première manigance annexe du deck séparé. Le Crâne Rouge gagne +1 ATQ par manigance annexe en jeu.','After adding threat at the start of the villain phase, reveal the top side scheme from the separate deck. Red Skull gains +1 ATK per side scheme in play.'],
  };
  add('ready','Vous êtes prêts','Ready to play',[reminders[id]!,['Le bouton de début de phase ajoute uniquement la menace et l’accélération : résolvez ensuite les effets particuliers ci-dessus sur votre table.','The phase button adds only threat and acceleration: resolve the special effects above at your table afterwards.'],[id==='s5_red_skull'&&campaignExpert?'Une défaite contre le Crâne Rouge en campagne Experte termine la campagne.':'En cas de défaite, vous pouvez retenter ce scénario sans avancer la campagne.',id==='s5_red_skull'&&campaignExpert?'Losing to Red Skull in an Expert campaign ends the campaign.':'After a defeat, you can retry this scenario without advancing the campaign.']]);
  return steps;
}
